// 80×79の全組み合わせの意味調査データベース（整理版）
// ジャンル: general(一般), surname(苗字), number(数量), none(意味なし)
// 形式: 「よみがな」または「よみがな/意味」

export type JukugoEntry = {
  word: string
  meaning: string
  type: 'general' | 'surname' | 'number' | 'none'
}

export const JUKUGO_DATABASE: JukugoEntry[] = [
  // ===== 一 =====
  { word: '一円', meaning: 'いちえん', type: 'number' },
  { word: '一下', meaning: 'いっか/いちどに', type: 'general' },
  { word: '一気', meaning: 'いっき/やすまずいきおいよく', type: 'general' },
  { word: '一休', meaning: 'ひとやすみ/すこしやすむこと', type: 'general' },
  { word: '一月', meaning: 'いちがつ', type: 'number' },
  { word: '一見', meaning: 'いっけん/ちょっとみること', type: 'general' },
  { word: '一口', meaning: 'ひとくち', type: 'number' },
  { word: '一山', meaning: 'ひとやま/ひとまとまり', type: 'general' },
  { word: '一手', meaning: 'ひとて', type: 'number' },
  { word: '一人', meaning: 'ひとり', type: 'number' },
  { word: '一生', meaning: 'いっしょう', type: 'number' },
  { word: '一石', meaning: 'いっせき/ひとつのいし', type: 'general' },
  { word: '一千', meaning: 'いっせん', type: 'number' },
  { word: '一村', meaning: 'いっそん/ひとつのむら', type: 'general' },
  { word: '一大', meaning: 'いちだい/とてもおおきな', type: 'general' },
  { word: '一中', meaning: 'いっちゅう/まんなかに', type: 'general' },
  { word: '一天', meaning: 'いってん/そらぜんたい', type: 'general' },
  { word: '一二', meaning: 'いちに', type: 'number' },
  { word: '一日', meaning: 'ついたち・いちにち', type: 'number' },
  { word: '一入', meaning: 'ひとしお/いっそう', type: 'general' },
  { word: '一年', meaning: 'いちねん', type: 'number' },
  { word: '一白', meaning: 'いっぱく/ひとばん', type: 'general' },
  { word: '一八', meaning: 'いっぱち', type: 'number' },
  { word: '一百', meaning: 'いっぴゃく', type: 'number' },
  { word: '一文', meaning: 'いちもん', type: 'number' },
  { word: '一本', meaning: 'いっぽん', type: 'number' },
  { word: '一名', meaning: 'いちめい', type: 'number' },
  { word: '一目', meaning: 'ひとめ', type: 'number' },
  { word: '一立', meaning: 'いちりつ/ひとつだけたつ', type: 'general' },
  { word: '一力', meaning: 'いちりき/ぜんりょく', type: 'general' },
  { word: '一六', meaning: 'いちろく', type: 'number' },

  // ===== 右 =====
  { word: '右手', meaning: 'みぎて/みぎのて', type: 'general' },
  { word: '右足', meaning: 'みぎあし/みぎのあし', type: 'general' },
  { word: '右目', meaning: 'みぎめ/みぎのめ', type: 'general' },
  { word: '右耳', meaning: 'みぎみみ/みぎのみみ', type: 'general' },
  { word: '右左', meaning: 'みぎひだり/りょうほう', type: 'general' },

  // ===== 雨 =====
  { word: '雨音', meaning: 'あまおと/あめのおと', type: 'general' },
  { word: '雨空', meaning: 'あまぞら/あめのそら', type: 'general' },
  { word: '雨水', meaning: 'あまみず/あめのみず', type: 'general' },
  { word: '雨天', meaning: 'うてん/あめのひ', type: 'general' },
  { word: '雨中', meaning: 'うちゅう/あめのなか', type: 'general' },
  { word: '雨上', meaning: 'あまあがり/あめがやむこと', type: 'general' },
  { word: '雨下', meaning: 'うか/あめがふる', type: 'general' },
  { word: '雨足', meaning: 'あまあし/あめのふりかた', type: 'general' },
  { word: '雨花', meaning: 'うか/あめとはな', type: 'general' },

  // ===== 円 =====
  { word: '円玉', meaning: 'えんだま/おかね', type: 'general' },
  { word: '円山', meaning: 'まるやま', type: 'surname' },

  // ===== 王 =====
  { word: '王子', meaning: 'おうじ/おうさまのこども', type: 'general' },
  { word: '王女', meaning: 'おうじょ/おうさまのむすめ', type: 'general' },
  { word: '王手', meaning: 'おうて/しょうぎでおうをねらう', type: 'general' },
  { word: '王立', meaning: 'おうりつ/おうさまがたてた', type: 'general' },

  // ===== 音 =====
  { word: '音山', meaning: 'おとやま', type: 'surname' },
  { word: '音田', meaning: 'おとだ', type: 'surname' },
  { word: '音川', meaning: 'おとかわ', type: 'surname' },

  // ===== 下 =====
  { word: '下火', meaning: 'したび/いきおいがよわまる', type: 'general' },
  { word: '下校', meaning: 'げこう/がっこうからかえる', type: 'general' },
  { word: '下山', meaning: 'げざん/やまからおりる', type: 'general' },
  { word: '下車', meaning: 'げしゃ/のりものからおりる', type: 'general' },
  { word: '下手', meaning: 'へた/じょうずでない', type: 'general' },
  { word: '下水', meaning: 'げすい/よごれたみず', type: 'general' },
  { word: '下足', meaning: 'げそく/くつをぬぐこと', type: 'general' },
  { word: '下田', meaning: 'しもだ', type: 'surname' },
  { word: '下町', meaning: 'したまち/しみんのまち', type: 'general' },
  { word: '下人', meaning: 'げにん/めしつかい', type: 'general' },
  { word: '下目', meaning: 'しため/したをみる', type: 'general' },
  { word: '下男', meaning: 'げなん/めしつかいのおとこ', type: 'general' },
  { word: '下女', meaning: 'げじょ/めしつかいのおんな', type: 'general' },
  { word: '下中', meaning: 'かちゅう/したのなか', type: 'general' },
  { word: '下金', meaning: 'したがね/したにしくかね', type: 'general' },

  // ===== 火 =====
  { word: '火気', meaning: 'かき/ひやねつ', type: 'general' },
  { word: '火口', meaning: 'かこう/かざんのあな', type: 'general' },
  { word: '火山', meaning: 'かざん/ひをふくやま', type: 'general' },
  { word: '火中', meaning: 'かちゅう/ひのなか', type: 'general' },
  { word: '火花', meaning: 'ひばな/ひのこ', type: 'general' },
  { word: '火力', meaning: 'かりょく/ひのちから', type: 'general' },
  { word: '火水', meaning: 'かすい/かようびすいようび', type: 'general' },
  { word: '火天', meaning: 'かてん/ひのてんき', type: 'general' },
  { word: '火玉', meaning: 'ひだま/ひのたま', type: 'general' },
  { word: '火金', meaning: 'かきん/かようびきんようび', type: 'general' },
  { word: '火木', meaning: 'かもく/かようびもくようび', type: 'general' },
  { word: '火土', meaning: 'かど/かようびどようび', type: 'general' },
  { word: '火日', meaning: 'かじつ/ひのひ', type: 'general' },
  { word: '火入', meaning: 'ひいれ/ひをいれること', type: 'general' },

  // ===== 花 =====
  { word: '花火', meaning: 'はなび/よるにあげるひ', type: 'general' },
  { word: '花見', meaning: 'はなみ/さくらをみる', type: 'general' },
  { word: '花木', meaning: 'かぼく/はながさくき', type: 'general' },
  { word: '花田', meaning: 'はなだ', type: 'surname' },
  { word: '花山', meaning: 'かざん', type: 'surname' },
  { word: '花金', meaning: 'はなきん/きんようびのよる', type: 'general' },
  { word: '花月', meaning: 'かげつ/はなとつき', type: 'general' },
  { word: '花草', meaning: 'かそう/はなとくさ', type: 'general' },
  { word: '花人', meaning: 'かじん/はなをいけるひと', type: 'general' },
  { word: '花水', meaning: 'はなみず/はなにあげるみず', type: 'general' },
  { word: '花川', meaning: 'はなかわ', type: 'surname' },
  { word: '花村', meaning: 'はなむら', type: 'surname' },
  { word: '花本', meaning: 'はなもと', type: 'surname' },
  { word: '花中', meaning: 'はななか', type: 'surname' },

  // ===== 貝 =====
  { word: '貝田', meaning: 'かいだ', type: 'surname' },
  { word: '貝山', meaning: 'かいやま', type: 'surname' },
  { word: '貝川', meaning: 'かいかわ', type: 'surname' },

  // ===== 学 =====
  { word: '学生', meaning: 'がくせい/べんきょうするひと', type: 'general' },
  { word: '学校', meaning: 'がっこう/べんきょうするばしょ', type: 'general' },
  { word: '学年', meaning: 'がくねん/がっこうのねんれい', type: 'general' },
  { word: '学力', meaning: 'がくりょく/べんきょうのちから', type: 'general' },
  { word: '学名', meaning: 'がくめい/いきもののなまえ', type: 'general' },
  { word: '学人', meaning: 'がくじん/べんきょうするひと', type: 'general' },
  { word: '学田', meaning: 'がくでん/がっこうのた', type: 'general' },

  // ===== 気 =====
  { word: '気力', meaning: 'きりょく/やるき', type: 'general' },
  { word: '気休', meaning: 'きやすめ/あんしんさせる', type: 'general' },
  { word: '気立', meaning: 'きだて/せいかく', type: 'general' },
  { word: '気山', meaning: 'きやま', type: 'surname' },
  { word: '気田', meaning: 'きだ', type: 'surname' },

  // ===== 九 =====
  { word: '九人', meaning: 'きゅうにん', type: 'number' },
  { word: '九日', meaning: 'ここのか', type: 'number' },
  { word: '九月', meaning: 'くがつ', type: 'number' },
  { word: '九十', meaning: 'きゅうじゅう', type: 'number' },
  { word: '九百', meaning: 'きゅうひゃく', type: 'number' },
  { word: '九千', meaning: 'きゅうせん', type: 'number' },

  // ===== 休 =====
  { word: '休火', meaning: 'きゅうか/きゅうかざん', type: 'general' },
  { word: '休校', meaning: 'きゅうこう/がっこうがやすみ', type: 'general' },
  { word: '休日', meaning: 'きゅうじつ/やすみのひ', type: 'general' },
  { word: '休学', meaning: 'きゅうがく/がっこうをやすむ', type: 'general' },
  { word: '休山', meaning: 'きゅうざん/やまをやすめる', type: 'general' },
  { word: '休田', meaning: 'きゅうでん/たをやすめる', type: 'general' },
  { word: '休足', meaning: 'きゅうそく/あしをやすめる', type: 'general' },

  // ===== 玉 =====
  { word: '玉石', meaning: 'ぎょくせき/よいものわるいもの', type: 'general' },
  { word: '玉入', meaning: 'たまいれ/うんどうかいのきょうぎ', type: 'general' },
  { word: '玉川', meaning: 'たまがわ', type: 'surname' },
  { word: '玉田', meaning: 'たまだ', type: 'surname' },
  { word: '玉木', meaning: 'たまき', type: 'surname' },
  { word: '玉山', meaning: 'たまやま', type: 'surname' },
  { word: '玉村', meaning: 'たまむら', type: 'surname' },
  { word: '玉虫', meaning: 'たまむし/きれいなむし', type: 'general' },
  { word: '玉水', meaning: 'たまみず/きれいなみず', type: 'general' },

  // ===== 金 =====
  { word: '金山', meaning: 'きんざん/きんがとれるやま', type: 'general' },
  { word: '金子', meaning: 'かねこ', type: 'surname' },
  { word: '金森', meaning: 'かなもり', type: 'surname' },
  { word: '金田', meaning: 'かねだ', type: 'surname' },
  { word: '金本', meaning: 'かねもと', type: 'surname' },
  { word: '金目', meaning: 'かねめ/おかねのかち', type: 'general' },
  { word: '金力', meaning: 'きんりょく/おかねのちから', type: 'general' },
  { word: '金川', meaning: 'かながわ', type: 'surname' },
  { word: '金村', meaning: 'かなむら', type: 'surname' },
  { word: '金中', meaning: 'かなか', type: 'surname' },
  { word: '金林', meaning: 'かなばやし', type: 'surname' },
  { word: '金石', meaning: 'きんせき/きんぞくといし', type: 'general' },
  { word: '金玉', meaning: 'きんぎょく/きんとたま', type: 'general' },
  { word: '金糸', meaning: 'きんし/きんいろのいと', type: 'general' },
  { word: '金土', meaning: 'きんど/きんようびどようび', type: 'general' },
  { word: '金口', meaning: 'きんこう/だいじなことば', type: 'general' },
  { word: '金火', meaning: 'きんか/きんぞくとひ', type: 'general' },
  { word: '金水', meaning: 'きんすい/きんぞくとみず', type: 'general' },
  { word: '金気', meaning: 'かなけ/きんぞくのにおい', type: 'general' },
  { word: '金文', meaning: 'きんぶん/むかしのもじ', type: 'general' },
  { word: '金字', meaning: 'きんじ/きんいろのもじ', type: 'general' },
  { word: '金竹', meaning: 'きんちく/きんぞくとたけ', type: 'general' },
  { word: '金木', meaning: 'かなき/きんもくせい', type: 'general' },

  // ===== 空 =====
  { word: '空気', meaning: 'くうき/いきをするもの', type: 'general' },
  { word: '空中', meaning: 'くうちゅう/そらのなか', type: 'general' },
  { word: '空車', meaning: 'くうしゃ/きゃくがいない', type: 'general' },
  { word: '空白', meaning: 'くうはく/なにもない', type: 'general' },
  { word: '空手', meaning: 'からて/ぶどう', type: 'general' },
  { word: '空耳', meaning: 'そらみみ/きこえたきがする', type: 'general' },
  { word: '空目', meaning: 'そらめ/みまちがい', type: 'general' },
  { word: '空木', meaning: 'うつぎ/しろいはなのき', type: 'general' },
  { word: '空田', meaning: 'そらた', type: 'surname' },
  { word: '空村', meaning: 'そらむら', type: 'surname' },
  { word: '空川', meaning: 'そらかわ', type: 'surname' },

  // ===== 月 =====
  { word: '月日', meaning: 'つきひ/としつきのながれ', type: 'general' },
  { word: '月見', meaning: 'つきみ/つきをみる', type: 'general' },
  { word: '月火', meaning: 'げっか/げつようびかようび', type: 'general' },
  { word: '月金', meaning: 'げっきん/げつようびきんようび', type: 'general' },
  { word: '月水', meaning: 'げっすい/げつようびすいようび', type: 'general' },
  { word: '月木', meaning: 'げつもく/げつようびもくようび', type: 'general' },
  { word: '月土', meaning: 'げつど/げつようびどようび', type: 'general' },
  { word: '月田', meaning: 'つきた', type: 'surname' },
  { word: '月山', meaning: 'がっさん/やまのなまえ', type: 'general' },
  { word: '月川', meaning: 'つきかわ', type: 'surname' },
  { word: '月村', meaning: 'つきむら', type: 'surname' },
  { word: '月本', meaning: 'つきもと', type: 'surname' },
  { word: '月下', meaning: 'げっか/つきのした', type: 'general' },
  { word: '月夕', meaning: 'げっせき/つきのよる', type: 'general' },
  { word: '月白', meaning: 'げっぱく/つきのひかり', type: 'general' },
  { word: '月花', meaning: 'げっか/つきとはな', type: 'general' },

  // ===== 犬 =====
  { word: '犬山', meaning: 'いぬやま', type: 'surname' },
  { word: '犬田', meaning: 'いぬた', type: 'surname' },
  { word: '犬川', meaning: 'いぬかわ', type: 'surname' },

  // ===== 見 =====
  { word: '見学', meaning: 'けんがく/みてまなぶ', type: 'general' },
  { word: '見本', meaning: 'みほん/おてほん', type: 'general' },
  { word: '見出', meaning: 'みだし/だいめい', type: 'general' },
  { word: '見立', meaning: 'みたて/なにかにみる', type: 'general' },
  { word: '見目', meaning: 'みめ/かおのよさ', type: 'general' },
  { word: '見山', meaning: 'みやま', type: 'surname' },
  { word: '見田', meaning: 'みた', type: 'surname' },
  { word: '見川', meaning: 'みかわ', type: 'surname' },

  // ===== 五 =====
  { word: '五円', meaning: 'ごえん', type: 'number' },
  { word: '五月', meaning: 'ごがつ', type: 'number' },
  { word: '五人', meaning: 'ごにん', type: 'number' },
  { word: '五十', meaning: 'ごじゅう', type: 'number' },
  { word: '五日', meaning: 'いつか', type: 'number' },
  { word: '五本', meaning: 'ごほん', type: 'number' },
  { word: '五木', meaning: 'いつき', type: 'surname' },
  { word: '五六', meaning: 'ごろく', type: 'number' },
  { word: '五百', meaning: 'ごひゃく', type: 'number' },
  { word: '五千', meaning: 'ごせん', type: 'number' },
  { word: '五山', meaning: 'ござん/ごつのやま', type: 'general' },
  { word: '五田', meaning: 'ごた', type: 'surname' },

  // ===== 口 =====
  { word: '口火', meaning: 'くちび/はじまり', type: 'general' },
  { word: '口車', meaning: 'くちぐるま/うまいことば', type: 'general' },
  { word: '口上', meaning: 'こうじょう/いうこと', type: 'general' },
  { word: '口出', meaning: 'くちだし/よけいなことをいう', type: 'general' },
  { word: '口入', meaning: 'くちいれ/しょうかいする', type: 'general' },
  { word: '口金', meaning: 'くちがね/いれぐちのかね', type: 'general' },
  { word: '口中', meaning: 'こうちゅう/くちのなか', type: 'general' },
  { word: '口山', meaning: 'くちやま', type: 'surname' },
  { word: '口田', meaning: 'くちだ', type: 'surname' },
  { word: '口川', meaning: 'くちかわ', type: 'surname' },

  // ===== 校 =====
  { word: '校正', meaning: 'こうせい/まちがいをなおす', type: 'general' },
  { word: '校下', meaning: 'こうか/がっこうのちいき', type: 'general' },
  { word: '校中', meaning: 'こうちゅう/がっこうのなか', type: 'general' },

  // ===== 左 =====
  { word: '左右', meaning: 'さゆう/ひだりとみぎ', type: 'general' },
  { word: '左手', meaning: 'ひだりて/ひだりのて', type: 'general' },
  { word: '左足', meaning: 'ひだりあし/ひだりのあし', type: 'general' },
  { word: '左目', meaning: 'ひだりめ/ひだりのめ', type: 'general' },
  { word: '左耳', meaning: 'ひだりみみ/ひだりのみみ', type: 'general' },

  // ===== 三 =====
  { word: '三月', meaning: 'さんがつ', type: 'number' },
  { word: '三人', meaning: 'さんにん', type: 'number' },
  { word: '三十', meaning: 'さんじゅう', type: 'number' },
  { word: '三日', meaning: 'みっか', type: 'number' },
  { word: '三本', meaning: 'さんぼん', type: 'number' },
  { word: '三木', meaning: 'みき', type: 'surname' },
  { word: '三四', meaning: 'さんし', type: 'number' },
  { word: '三百', meaning: 'さんびゃく', type: 'number' },
  { word: '三千', meaning: 'さんぜん', type: 'number' },

  // ===== 山 =====
  { word: '山火', meaning: 'やまび/やまのかじ', type: 'general' },
  { word: '山林', meaning: 'さんりん/やまのもり', type: 'general' },
  { word: '山川', meaning: 'やまかわ/やまとかわ', type: 'general' },
  { word: '山中', meaning: 'さんちゅう/やまのなか', type: 'general' },
  { word: '山村', meaning: 'さんそん/やまのむら', type: 'general' },
  { word: '山口', meaning: 'やまぐち', type: 'surname' },
  { word: '山田', meaning: 'やまだ', type: 'surname' },
  { word: '山本', meaning: 'やまもと', type: 'surname' },
  { word: '山上', meaning: 'やまがみ', type: 'surname' },
  { word: '山下', meaning: 'やました', type: 'surname' },
  { word: '山水', meaning: 'さんすい/やまとみず', type: 'general' },
  { word: '山草', meaning: 'やまくさ/やまのくさ', type: 'general' },
  { word: '山石', meaning: 'やまいし/やまのいし', type: 'general' },
  { word: '山土', meaning: 'やまつち/やまのつち', type: 'general' },
  { word: '山犬', meaning: 'やまいぬ/おおかみ', type: 'general' },
  { word: '山王', meaning: 'さんのう/やまのかみさま', type: 'general' },
  { word: '山竹', meaning: 'やまたけ/やまのたけ', type: 'general' },
  { word: '山人', meaning: 'さんじん/やまにすむひと', type: 'general' },
  { word: '山女', meaning: 'やまめ/かわのさかな', type: 'general' },
  { word: '山男', meaning: 'やまおとこ/やまにすむおとこ', type: 'general' },
  { word: '山車', meaning: 'だし/おまつりのくるま', type: 'general' },
  { word: '山手', meaning: 'やまて/やまがわ', type: 'general' },

  // ===== 子 =====
  { word: '子犬', meaning: 'こいぬ/いぬのこども', type: 'general' },
  { word: '子女', meaning: 'しじょ/こどもたち', type: 'general' },
  { word: '子山', meaning: 'こやま', type: 'surname' },
  { word: '子田', meaning: 'こだ', type: 'surname' },
  { word: '子川', meaning: 'こかわ', type: 'surname' },
  { word: '子年', meaning: 'ねどし/ねずみどし', type: 'general' },
  { word: '子日', meaning: 'ねのひ/ねのつくひ', type: 'general' },
  { word: '子月', meaning: 'しげつ/じゅういちがつ', type: 'general' },

  // ===== 四 =====
  { word: '四月', meaning: 'しがつ', type: 'number' },
  { word: '四人', meaning: 'よにん', type: 'number' },
  { word: '四十', meaning: 'よんじゅう', type: 'number' },
  { word: '四日', meaning: 'よっか', type: 'number' },
  { word: '四本', meaning: 'よんほん', type: 'number' },
  { word: '四五', meaning: 'しご', type: 'number' },
  { word: '四百', meaning: 'よんひゃく', type: 'number' },
  { word: '四千', meaning: 'よんせん', type: 'number' },

  // ===== 糸 =====
  { word: '糸口', meaning: 'いとぐち/はじまり', type: 'general' },
  { word: '糸目', meaning: 'いとめ/いとのあと', type: 'general' },
  { word: '糸山', meaning: 'いとやま', type: 'surname' },
  { word: '糸田', meaning: 'いとだ', type: 'surname' },
  { word: '糸川', meaning: 'いとかわ', type: 'surname' },
  { word: '糸村', meaning: 'いとむら', type: 'surname' },

  // ===== 字 =====
  { word: '字名', meaning: 'あざな/ちいさなちめい', type: 'general' },
  { word: '字山', meaning: 'じやま', type: 'surname' },
  { word: '字田', meaning: 'じた', type: 'surname' },

  // ===== 耳 =====
  { word: '耳目', meaning: 'じもく/みみとめ', type: 'general' },
  { word: '耳山', meaning: 'みみやま', type: 'surname' },
  { word: '耳田', meaning: 'みみた', type: 'surname' },
  { word: '耳石', meaning: 'じせき/みみのいし', type: 'general' },

  // ===== 七 =====
  { word: '七月', meaning: 'しちがつ', type: 'number' },
  { word: '七人', meaning: 'しちにん', type: 'number' },
  { word: '七十', meaning: 'ななじゅう', type: 'number' },
  { word: '七日', meaning: 'なのか', type: 'number' },
  { word: '七夕', meaning: 'たなばた/なつのおまつり', type: 'general' },
  { word: '七八', meaning: 'しちはち', type: 'number' },
  { word: '七百', meaning: 'ななひゃく', type: 'number' },
  { word: '七千', meaning: 'ななせん', type: 'number' },

  // ===== 車 =====
  { word: '車中', meaning: 'しゃちゅう/くるまのなか', type: 'general' },
  { word: '車力', meaning: 'しゃりき/くるまをひくちから', type: 'general' },
  { word: '車山', meaning: 'くるまやま', type: 'surname' },
  { word: '車田', meaning: 'くるまだ', type: 'surname' },
  { word: '車川', meaning: 'くるまかわ', type: 'surname' },

  // ===== 手 =====
  { word: '手足', meaning: 'てあし/てとあし', type: 'general' },
  { word: '手本', meaning: 'てほん/おてほん', type: 'general' },
  { word: '手入', meaning: 'ていれ/せわをする', type: 'general' },
  { word: '手先', meaning: 'てさき/ゆびさき', type: 'general' },
  { word: '手下', meaning: 'てした/ぶか', type: 'general' },
  { word: '手中', meaning: 'しゅちゅう/てのなか', type: 'general' },
  { word: '手口', meaning: 'てぐち/やりかた', type: 'general' },
  { word: '手水', meaning: 'ちょうず/てをあらうみず', type: 'general' },
  { word: '手金', meaning: 'てきん/まえばらいきん', type: 'general' },
  { word: '手玉', meaning: 'てだま/おてだま', type: 'general' },
  { word: '手車', meaning: 'てぐるま/ておしぐるま', type: 'general' },
  { word: '手力', meaning: 'しゅりき/てのちから', type: 'general' },
  { word: '手山', meaning: 'てやま', type: 'surname' },
  { word: '手田', meaning: 'てだ', type: 'surname' },
  { word: '手川', meaning: 'てかわ', type: 'surname' },
  { word: '手村', meaning: 'てむら', type: 'surname' },

  // ===== 十 =====
  { word: '十円', meaning: 'じゅうえん', type: 'number' },
  { word: '十月', meaning: 'じゅうがつ', type: 'number' },
  { word: '十字', meaning: 'じゅうじ', type: 'number' },
  { word: '十人', meaning: 'じゅうにん', type: 'number' },
  { word: '十中', meaning: 'じゅっちゅう/じゅうのうち', type: 'general' },
  { word: '十日', meaning: 'とおか', type: 'number' },
  { word: '十本', meaning: 'じゅっぽん', type: 'number' },
  { word: '十一', meaning: 'じゅういち', type: 'number' },
  { word: '十二', meaning: 'じゅうに', type: 'number' },
  { word: '十三', meaning: 'じゅうさん', type: 'number' },
  { word: '十四', meaning: 'じゅうし', type: 'number' },
  { word: '十五', meaning: 'じゅうご', type: 'number' },
  { word: '十六', meaning: 'じゅうろく', type: 'number' },
  { word: '十七', meaning: 'じゅうしち', type: 'number' },
  { word: '十八', meaning: 'じゅうはち', type: 'number' },
  { word: '十九', meaning: 'じゅうく', type: 'number' },

  // ===== 出 =====
  { word: '出入', meaning: 'でいり/でたりはいったり', type: 'general' },
  { word: '出口', meaning: 'でぐち/でるところ', type: 'general' },
  { word: '出火', meaning: 'しゅっか/かじがおきる', type: 'general' },
  { word: '出生', meaning: 'しゅっせい/うまれる', type: 'general' },
  { word: '出金', meaning: 'しゅっきん/おかねをだす', type: 'general' },
  { word: '出力', meaning: 'しゅつりょく/ちからをだす', type: 'general' },
  { word: '出目', meaning: 'でめ/めがでている', type: 'general' },
  { word: '出足', meaning: 'であし/でだし', type: 'general' },
  { word: '出水', meaning: 'でみず/こうずい', type: 'general' },
  { word: '出土', meaning: 'しゅつど/つちからでる', type: 'general' },
  { word: '出立', meaning: 'しゅったつ/たびにでる', type: 'general' },
  { word: '出先', meaning: 'でさき/でかけたさき', type: 'general' },
  { word: '出山', meaning: 'でやま', type: 'surname' },
  { word: '出田', meaning: 'でた', type: 'surname' },
  { word: '出川', meaning: 'でがわ', type: 'surname' },

  // ===== 女 =====
  { word: '女王', meaning: 'じょおう/おんなのおうさま', type: 'general' },
  { word: '女子', meaning: 'じょし/おんなのこ', type: 'general' },
  { word: '女中', meaning: 'じょちゅう/めしつかい', type: 'general' },
  { word: '女人', meaning: 'にょにん/おんなのひと', type: 'general' },
  { word: '女手', meaning: 'おんなで/おんなのちから', type: 'general' },
  { word: '女山', meaning: 'おんなやま', type: 'surname' },
  { word: '女川', meaning: 'おながわ', type: 'surname' },

  // ===== 小 =====
  { word: '小人', meaning: 'こびと/ちいさいひと', type: 'general' },
  { word: '小石', meaning: 'こいし/ちいさいいし', type: 'general' },
  { word: '小川', meaning: 'おがわ', type: 'surname' },
  { word: '小山', meaning: 'こやま', type: 'surname' },
  { word: '小林', meaning: 'こばやし', type: 'surname' },
  { word: '小田', meaning: 'おだ', type: 'surname' },
  { word: '小雨', meaning: 'こさめ/よわいあめ', type: 'general' },
  { word: '小学', meaning: 'しょうがく/しょうがっこう', type: 'general' },
  { word: '小休', meaning: 'しょうきゅう/すこしやすむ', type: 'general' },
  { word: '小金', meaning: 'こがね/すこしのおかね', type: 'general' },
  { word: '小犬', meaning: 'こいぬ/いぬのこ', type: 'general' },
  { word: '小火', meaning: 'ぼや/ちいさいかじ', type: 'general' },
  { word: '小手', meaning: 'こて/けんどうのどうぐ', type: 'general' },
  { word: '小木', meaning: 'こぎ', type: 'surname' },
  { word: '小口', meaning: 'こぐち/すくないりょう', type: 'general' },
  { word: '小目', meaning: 'こめ/ちいさいめ', type: 'general' },
  { word: '小耳', meaning: 'こみみ/ちょっときく', type: 'general' },
  { word: '小足', meaning: 'こあし/みじかいあし', type: 'general' },
  { word: '小字', meaning: 'こあざ/ちいきのなまえ', type: 'general' },
  { word: '小玉', meaning: 'こだま/ちいさいたま', type: 'general' },
  { word: '小水', meaning: 'しょうすい/おしっこ', type: 'general' },
  { word: '小入', meaning: 'こいり/すこしはいる', type: 'general' },
  { word: '小出', meaning: 'こいで', type: 'surname' },
  { word: '小男', meaning: 'こおとこ/ちいさいおとこ', type: 'general' },
  { word: '小女', meaning: 'こおんな/ちいさいおんな', type: 'general' },

  // ===== 上 =====
  { word: '上下', meaning: 'じょうげ/うえとした', type: 'general' },
  { word: '上手', meaning: 'じょうず/とくいな', type: 'general' },
  { word: '上気', meaning: 'じょうき/かおがあかくなる', type: 'general' },
  { word: '上田', meaning: 'うえだ', type: 'surname' },
  { word: '上山', meaning: 'うえやま', type: 'surname' },
  { word: '上中', meaning: 'じょうちゅう/うえとまんなか', type: 'general' },
  { word: '上空', meaning: 'じょうくう/そらのうえ', type: 'general' },
  { word: '上火', meaning: 'じょうか/うえのひ', type: 'general' },
  { word: '上水', meaning: 'じょうすい/きれいなみず', type: 'general' },
  { word: '上目', meaning: 'うわめ/うえをみるめ', type: 'general' },
  { word: '上人', meaning: 'しょうにん/えらいおぼうさん', type: 'general' },

  // ===== 森 =====
  { word: '森林', meaning: 'しんりん/もりとはやし', type: 'general' },
  { word: '森田', meaning: 'もりた', type: 'surname' },
  { word: '森山', meaning: 'もりやま', type: 'surname' },
  { word: '森本', meaning: 'もりもと', type: 'surname' },
  { word: '森川', meaning: 'もりかわ', type: 'surname' },
  { word: '森中', meaning: 'もりなか', type: 'surname' },

  // ===== 人 =====
  { word: '人口', meaning: 'じんこう/ひとのかず', type: 'general' },
  { word: '人名', meaning: 'じんめい/ひとのなまえ', type: 'general' },
  { word: '人力', meaning: 'じんりき/ひとのちから', type: 'general' },
  { word: '人生', meaning: 'じんせい/いきていること', type: 'general' },
  { word: '人目', meaning: 'ひとめ/ひとのめ', type: 'general' },
  { word: '人気', meaning: 'にんき/ひとにすかれる', type: 'general' },
  { word: '人手', meaning: 'ひとで/てつだうひと', type: 'general' },
  { word: '人中', meaning: 'じんちゅう/ひとのなか', type: 'general' },
  { word: '人足', meaning: 'にんそく/はたらくひと', type: 'general' },
  { word: '人山', meaning: 'ひとやま/ひとがたくさん', type: 'general' },
  { word: '人出', meaning: 'ひとで/ひとがでる', type: 'general' },
  { word: '人見', meaning: 'ひとみ', type: 'surname' },
  { word: '人田', meaning: 'ひとだ', type: 'surname' },
  { word: '人川', meaning: 'ひとかわ', type: 'surname' },

  // ===== 水 =====
  { word: '水田', meaning: 'すいでん/いねをつくるた', type: 'general' },
  { word: '水中', meaning: 'すいちゅう/みずのなか', type: 'general' },
  { word: '水車', meaning: 'すいしゃ/みずでまわるくるま', type: 'general' },
  { word: '水力', meaning: 'すいりょく/みずのちから', type: 'general' },
  { word: '水気', meaning: 'みずけ/しめりけ', type: 'general' },
  { word: '水玉', meaning: 'みずたま/まるいもよう', type: 'general' },
  { word: '水草', meaning: 'みずくさ/みずのなかのくさ', type: 'general' },
  { word: '水虫', meaning: 'みずむし/あしのびょうき', type: 'general' },
  { word: '水金', meaning: 'すいきん/すいようびきんようび', type: 'general' },
  { word: '水口', meaning: 'みなくち', type: 'surname' },
  { word: '水本', meaning: 'みずもと', type: 'surname' },
  { word: '水川', meaning: 'みずかわ', type: 'surname' },
  { word: '水山', meaning: 'みずやま', type: 'surname' },
  { word: '水村', meaning: 'みずむら', type: 'surname' },
  { word: '水上', meaning: 'すいじょう/みずのうえ', type: 'general' },
  { word: '水下', meaning: 'すいか/みずのした', type: 'general' },
  { word: '水木', meaning: 'みずき/すいようびもくようび', type: 'general' },
  { word: '水入', meaning: 'みずいり/みずがはいる', type: 'general' },
  { word: '水出', meaning: 'みずで/みずがでる', type: 'general' },
  { word: '水手', meaning: 'かこ/ふねのひと', type: 'general' },
  { word: '水生', meaning: 'すいせい/みずにすむ', type: 'general' },
  { word: '水天', meaning: 'すいてん/みずとそら', type: 'general' },
  { word: '水日', meaning: 'すいじつ/すいようびにちようび', type: 'general' },
  { word: '水月', meaning: 'すいげつ/みずにうつるつき', type: 'general' },
  { word: '水石', meaning: 'すいせき/みずといし', type: 'general' },
  { word: '水火', meaning: 'すいか/みずとひ', type: 'general' },

  // ===== 正 =====
  { word: '正月', meaning: 'しょうがつ/おしょうがつ', type: 'general' },
  { word: '正気', meaning: 'しょうき/ただしいこころ', type: 'general' },
  { word: '正文', meaning: 'せいぶん/ただしいぶんしょう', type: 'general' },
  { word: '正本', meaning: 'せいほん/ほんもの', type: 'general' },
  { word: '正目', meaning: 'まさめ/きのもくめ', type: 'general' },
  { word: '正木', meaning: 'まさき', type: 'surname' },
  { word: '正田', meaning: 'しょうだ', type: 'surname' },
  { word: '正人', meaning: 'せいじん/ただしいひと', type: 'general' },
  { word: '正中', meaning: 'せいちゅう/まんなか', type: 'general' },
  { word: '正大', meaning: 'せいだい/ただしくておおきい', type: 'general' },
  { word: '正名', meaning: 'せいめい/ただしいなまえ', type: 'general' },
  { word: '正立', meaning: 'せいりつ/まっすぐたつ', type: 'general' },
  { word: '正力', meaning: 'しょうりき', type: 'surname' },

  // ===== 生 =====
  { word: '生年', meaning: 'せいねん/うまれたとし', type: 'general' },
  { word: '生花', meaning: 'いけばな/はなをいける', type: 'general' },
  { word: '生気', meaning: 'せいき/いきいきしたかんじ', type: 'general' },
  { word: '生水', meaning: 'なまみず/わかしてないみず', type: 'general' },
  { word: '生日', meaning: 'せいじつ/うまれたひ', type: 'general' },
  { word: '生田', meaning: 'いくた', type: 'surname' },
  { word: '生糸', meaning: 'きいと/かいこのいと', type: 'general' },
  { word: '生木', meaning: 'なまき/いきているき', type: 'general' },
  { word: '生竹', meaning: 'なまたけ/あおいたけ', type: 'general' },
  { word: '生石', meaning: 'なまいし/やいてないいし', type: 'general' },
  { word: '生土', meaning: 'なまつち/かわいていないつち', type: 'general' },
  { word: '生足', meaning: 'なまあし/くつしたをはかない', type: 'general' },
  { word: '生口', meaning: 'いけくち/いきているひと', type: 'general' },
  { word: '生出', meaning: 'おいで', type: 'surname' },
  { word: '生立', meaning: 'せいりつ/そだち', type: 'general' },
  { word: '生中', meaning: 'なまちゅう/なまびーるちゅう', type: 'general' },
  { word: '生月', meaning: 'せいげつ/うまれたつき', type: 'general' },
  { word: '生山', meaning: 'いくやま', type: 'surname' },
  { word: '生川', meaning: 'いくかわ', type: 'surname' },
  { word: '生村', meaning: 'いくむら', type: 'surname' },

  // ===== 青 =====
  { word: '青年', meaning: 'せいねん/わかいひと', type: 'general' },
  { word: '青空', meaning: 'あおぞら/あおいそら', type: 'general' },
  { word: '青虫', meaning: 'あおむし/あおいむし', type: 'general' },
  { word: '青竹', meaning: 'あおだけ/あおいたけ', type: 'general' },
  { word: '青草', meaning: 'あおくさ/あおいくさ', type: 'general' },
  { word: '青山', meaning: 'あおやま', type: 'surname' },
  { word: '青木', meaning: 'あおき', type: 'surname' },
  { word: '青田', meaning: 'あおた', type: 'surname' },
  { word: '青天', meaning: 'せいてん/はれたそら', type: 'general' },
  { word: '青白', meaning: 'あおじろ/かおがしろい', type: 'general' },
  { word: '青火', meaning: 'あおび/あおいほのお', type: 'general' },
  { word: '青水', meaning: 'あおみず/あおいみず', type: 'general' },

  // ===== 夕 =====
  { word: '夕日', meaning: 'ゆうひ/しずむたいよう', type: 'general' },
  { word: '夕立', meaning: 'ゆうだち/ゆうがたのあめ', type: 'general' },
  { word: '夕空', meaning: 'ゆうぞら/ゆうがたのそら', type: 'general' },
  { word: '夕月', meaning: 'ゆうづき/ゆうがたのつき', type: 'general' },
  { word: '夕雨', meaning: 'ゆうさめ/ゆうがたのあめ', type: 'general' },
  { word: '夕山', meaning: 'ゆうやま', type: 'surname' },
  { word: '夕田', meaning: 'ゆうだ', type: 'surname' },
  { word: '夕川', meaning: 'ゆうかわ', type: 'surname' },

  // ===== 石 =====
  { word: '石田', meaning: 'いしだ', type: 'surname' },
  { word: '石山', meaning: 'いしやま', type: 'surname' },
  { word: '石川', meaning: 'いしかわ', type: 'surname' },
  { word: '石村', meaning: 'いしむら', type: 'surname' },
  { word: '石中', meaning: 'いしなか', type: 'surname' },
  { word: '石本', meaning: 'いしもと', type: 'surname' },
  { word: '石林', meaning: 'いしばやし', type: 'surname' },
  { word: '石火', meaning: 'せっか/いしをうつひ', type: 'general' },
  { word: '石水', meaning: 'いしみず/いしのみず', type: 'general' },
  { word: '石目', meaning: 'いしめ/いしのもよう', type: 'general' },
  { word: '石竹', meaning: 'せきちく/はなのなまえ', type: 'general' },

  // ===== 赤 =====
  { word: '赤字', meaning: 'あかじ/そんをする', type: 'general' },
  { word: '赤木', meaning: 'あかぎ', type: 'surname' },
  { word: '赤田', meaning: 'あかだ', type: 'surname' },
  { word: '赤川', meaning: 'あかがわ', type: 'surname' },
  { word: '赤山', meaning: 'あかやま', type: 'surname' },
  { word: '赤村', meaning: 'あかむら', type: 'surname' },
  { word: '赤石', meaning: 'あかいし', type: 'surname' },
  { word: '赤土', meaning: 'あかつち/あかいつち', type: 'general' },
  { word: '赤金', meaning: 'あかがね/どう', type: 'general' },
  { word: '赤目', meaning: 'あかめ/あかいめ', type: 'general' },
  { word: '赤虫', meaning: 'あかむし/あかいむし', type: 'general' },
  { word: '赤貝', meaning: 'あかがい/あかいかい', type: 'general' },
  { word: '赤白', meaning: 'あかしろ/あかとしろ', type: 'general' },
  { word: '赤火', meaning: 'あかび/あかいひ', type: 'general' },
  { word: '赤口', meaning: 'しゃっこう/ろくようのひとつ', type: 'general' },

  // ===== 千 =====
  { word: '千円', meaning: 'せんえん', type: 'number' },
  { word: '千人', meaning: 'せんにん', type: 'number' },
  { word: '千本', meaning: 'せんぼん', type: 'number' },
  { word: '千年', meaning: 'せんねん', type: 'number' },
  { word: '千日', meaning: 'せんにち', type: 'number' },
  { word: '千田', meaning: 'ちだ', type: 'surname' },
  { word: '千川', meaning: 'せんかわ', type: 'surname' },
  { word: '千山', meaning: 'せんざん/たくさんのやま', type: 'general' },
  { word: '千村', meaning: 'ちむら', type: 'surname' },
  { word: '千石', meaning: 'せんごく', type: 'surname' },
  { word: '千草', meaning: 'ちぐさ/いろいろなくさ', type: 'general' },
  { word: '千金', meaning: 'せんきん/たいせつなもの', type: 'general' },
  { word: '千手', meaning: 'せんじゅ/たくさんのて', type: 'general' },
  { word: '千百', meaning: 'せんひゃく', type: 'number' },
  { word: '百千', meaning: 'ひゃくせん・ももち', type: 'number' },

  // ===== 川 =====
  { word: '川上', meaning: 'かわかみ/かわのうえ', type: 'general' },
  { word: '川下', meaning: 'かわしも/かわのした', type: 'general' },
  { word: '川中', meaning: 'かわなか/かわのなか', type: 'general' },
  { word: '川口', meaning: 'かわぐち', type: 'surname' },
  { word: '川田', meaning: 'かわた', type: 'surname' },
  { word: '川村', meaning: 'かわむら', type: 'surname' },
  { word: '川本', meaning: 'かわもと', type: 'surname' },
  { word: '川林', meaning: 'かわばやし', type: 'surname' },
  { word: '川手', meaning: 'かわて/かわべ', type: 'general' },
  { word: '川水', meaning: 'かわみず/かわのみず', type: 'general' },
  { word: '川石', meaning: 'かわいし/かわのいし', type: 'general' },
  { word: '川草', meaning: 'かわくさ/かわのくさ', type: 'general' },
  { word: '川虫', meaning: 'かわむし/かわのむし', type: 'general' },

  // ===== 先 =====
  { word: '先人', meaning: 'せんじん/むかしのひと', type: 'general' },
  { word: '先手', meaning: 'せんて/さきにうごく', type: 'general' },
  { word: '先月', meaning: 'せんげつ/まえのつき', type: 'general' },
  { word: '先日', meaning: 'せんじつ/このまえ', type: 'general' },
  { word: '先生', meaning: 'せんせい/おしえるひと', type: 'general' },
  { word: '先入', meaning: 'せんにゅう/さきにいれる', type: 'general' },
  { word: '先年', meaning: 'せんねん/まえのとし', type: 'general' },
  { word: '先立', meaning: 'せんりつ/さきにたつ', type: 'general' },
  { word: '先山', meaning: 'さきやま', type: 'surname' },
  { word: '先田', meaning: 'さきだ', type: 'surname' },
  { word: '先川', meaning: 'さきかわ', type: 'surname' },
  { word: '先金', meaning: 'さきがね/まえばらい', type: 'general' },

  // ===== 早 =====
  { word: '早口', meaning: 'はやくち/はやくしゃべる', type: 'general' },
  { word: '早足', meaning: 'はやあし/はやくあるく', type: 'general' },
  { word: '早川', meaning: 'はやかわ', type: 'surname' },
  { word: '早山', meaning: 'はややま', type: 'surname' },
  { word: '早田', meaning: 'はやた', type: 'surname' },
  { word: '早手', meaning: 'はやて/はやいうごき', type: 'general' },
  { word: '早目', meaning: 'はやめ/はやいうちに', type: 'general' },
  { word: '早生', meaning: 'わせ/はやくそだつ', type: 'general' },
  { word: '早天', meaning: 'そうてん/あさはやく', type: 'general' },

  // ===== 草 =====
  { word: '草花', meaning: 'くさばな/くさとはな', type: 'general' },
  { word: '草木', meaning: 'くさき/くさとき', type: 'general' },
  { word: '草虫', meaning: 'くさむし/くさのむし', type: 'general' },
  { word: '草田', meaning: 'くさだ', type: 'surname' },
  { word: '草川', meaning: 'くさかわ', type: 'surname' },
  { word: '草山', meaning: 'くさやま', type: 'surname' },
  { word: '草火', meaning: 'くさび/くさのひ', type: 'general' },
  { word: '草土', meaning: 'くさつち/くさとつち', type: 'general' },
  { word: '草人', meaning: 'くさびと/くさのひと', type: 'general' },
  { word: '草生', meaning: 'くさふ/くさがはえる', type: 'general' },
  { word: '草中', meaning: 'くさなか/くさのなか', type: 'general' },

  // ===== 足 =====
  { word: '足音', meaning: 'あしおと/あるくおと', type: 'general' },
  { word: '足下', meaning: 'あしもと/あしのした', type: 'general' },
  { word: '足山', meaning: 'あしやま', type: 'surname' },
  { word: '足田', meaning: 'あしだ', type: 'surname' },
  { word: '足川', meaning: 'あしかわ', type: 'surname' },
  { word: '足手', meaning: 'あして/じゃま', type: 'general' },
  { word: '足力', meaning: 'そくりき/あしのちから', type: 'general' },
  { word: '足金', meaning: 'あしがね/あしにつけるかね', type: 'general' },

  // ===== 村 =====
  { word: '村人', meaning: 'むらびと/むらにすむひと', type: 'general' },
  { word: '村上', meaning: 'むらかみ', type: 'surname' },
  { word: '村田', meaning: 'むらた', type: 'surname' },
  { word: '村山', meaning: 'むらやま', type: 'surname' },
  { word: '村中', meaning: 'むらなか', type: 'surname' },
  { word: '村川', meaning: 'むらかわ', type: 'surname' },
  { word: '村本', meaning: 'むらもと', type: 'surname' },
  { word: '村林', meaning: 'むらばやし', type: 'surname' },
  { word: '村名', meaning: 'そんめい/むらのなまえ', type: 'general' },

  // ===== 大 =====
  { word: '大人', meaning: 'おとな/おおきいひと', type: 'general' },
  { word: '大火', meaning: 'たいか/おおきいかじ', type: 'general' },
  { word: '大雨', meaning: 'おおあめ/つよいあめ', type: 'general' },
  { word: '大木', meaning: 'たいぼく/おおきいき', type: 'general' },
  { word: '大金', meaning: 'たいきん/たくさんのおかね', type: 'general' },
  { word: '大空', meaning: 'おおぞら/ひろいそら', type: 'general' },
  { word: '大小', meaning: 'だいしょう/おおきいとちいさい', type: 'general' },
  { word: '大水', meaning: 'おおみず/こうずい', type: 'general' },
  { word: '大石', meaning: 'おおいし/おおきいいし', type: 'general' },
  { word: '大中', meaning: 'だいちゅう/おおきいとちゅう', type: 'general' },
  { word: '大学', meaning: 'だいがく/べんきょうするところ', type: 'general' },
  { word: '大山', meaning: 'おおやま', type: 'surname' },
  { word: '大田', meaning: 'おおた', type: 'surname' },
  { word: '大川', meaning: 'おおかわ', type: 'surname' },
  { word: '大林', meaning: 'おおばやし', type: 'surname' },
  { word: '大森', meaning: 'おおもり', type: 'surname' },
  { word: '大口', meaning: 'おおぐち/おおきいくち', type: 'general' },
  { word: '大村', meaning: 'おおむら', type: 'surname' },
  { word: '大本', meaning: 'おおもと', type: 'surname' },
  { word: '大手', meaning: 'おおて/おおきいかいしゃ', type: 'general' },
  { word: '大目', meaning: 'おおめ/おおめにみる', type: 'general' },
  { word: '大耳', meaning: 'おおみみ/おおきいみみ', type: 'general' },
  { word: '大足', meaning: 'おおあし/おおきいあし', type: 'general' },
  { word: '大字', meaning: 'おおあざ/ちいきのなまえ', type: 'general' },
  { word: '大玉', meaning: 'おおだま/おおきいたま', type: 'general' },
  { word: '大入', meaning: 'おおいり/たくさんはいる', type: 'general' },
  { word: '大名', meaning: 'だいみょう/むかしのとの', type: 'general' },
  { word: '大王', meaning: 'だいおう/おおきいおう', type: 'general' },
  { word: '大正', meaning: 'たいしょう/じだいのなまえ', type: 'general' },
  { word: '大力', meaning: 'だいりき/おおきいちから', type: 'general' },
  { word: '大男', meaning: 'おおおとこ/おおきいおとこ', type: 'general' },
  { word: '大女', meaning: 'おおおんな/おおきいおんな', type: 'general' },
  { word: '大気', meaning: 'たいき/ちきゅうのくうき', type: 'general' },
  { word: '大月', meaning: 'おおつき', type: 'surname' },
  { word: '大日', meaning: 'だいにち/おおきいひ', type: 'general' },
  { word: '大犬', meaning: 'おおいぬ/おおきいいぬ', type: 'general' },

  // ===== 男 =====
  { word: '男子', meaning: 'だんし/おとこのこ', type: 'general' },
  { word: '男女', meaning: 'だんじょ/おとことおんな', type: 'general' },
  { word: '男手', meaning: 'おとこで/おとこのちから', type: 'general' },
  { word: '男人', meaning: 'おとこびと/おとこのひと', type: 'general' },
  { word: '男山', meaning: 'おとこやま/おとこらしいやま', type: 'general' },

  // ===== 竹 =====
  { word: '竹林', meaning: 'ちくりん/たけのはやし', type: 'general' },
  { word: '竹中', meaning: 'たけなか', type: 'surname' },
  { word: '竹田', meaning: 'たけだ', type: 'surname' },
  { word: '竹本', meaning: 'たけもと', type: 'surname' },
  { word: '竹村', meaning: 'たけむら', type: 'surname' },
  { word: '竹山', meaning: 'たけやま', type: 'surname' },
  { word: '竹川', meaning: 'たけかわ', type: 'surname' },
  { word: '竹石', meaning: 'たけいし', type: 'surname' },
  { word: '竹火', meaning: 'ちくか/たけのひ', type: 'general' },
  { word: '竹水', meaning: 'ちくすい/たけのみず', type: 'general' },
  { word: '竹人', meaning: 'ちくじん/たけをあつかうひと', type: 'general' },
  { word: '竹生', meaning: 'ちくぶ/たけがはえる', type: 'general' },
  { word: '竹目', meaning: 'たけめ/たけのもよう', type: 'general' },

  // ===== 中 =====
  { word: '中火', meaning: 'ちゅうび/ふつうのひ', type: 'general' },
  { word: '中学', meaning: 'ちゅうがく/ちゅうがっこう', type: 'general' },
  { word: '中年', meaning: 'ちゅうねん/まんなかのとし', type: 'general' },
  { word: '中村', meaning: 'なかむら', type: 'surname' },
  { word: '中山', meaning: 'なかやま', type: 'surname' },
  { word: '中田', meaning: 'なかた', type: 'surname' },
  { word: '中川', meaning: 'なかがわ', type: 'surname' },
  { word: '中日', meaning: 'ちゅうにち/にほんとちゅうごく', type: 'general' },
  { word: '中本', meaning: 'なかもと', type: 'surname' },
  { word: '中林', meaning: 'なかばやし', type: 'surname' },
  { word: '中森', meaning: 'なかもり', type: 'surname' },
  { word: '中石', meaning: 'なかいし', type: 'surname' },
  { word: '中上', meaning: 'ちゅうじょう/まんなかよりうえ', type: 'general' },
  { word: '中下', meaning: 'ちゅうげ/まんなかよりした', type: 'general' },
  { word: '中立', meaning: 'ちゅうりつ/どちらにもつかない', type: 'general' },
  { word: '中入', meaning: 'なかいり/きゅうけい', type: 'general' },
  { word: '中出', meaning: 'なかで/なかからでる', type: 'general' },
  { word: '中天', meaning: 'ちゅうてん/そらのまんなか', type: 'general' },
  { word: '中空', meaning: 'ちゅうくう/くうちゅう', type: 'general' },
  { word: '中人', meaning: 'ちゅうにん/ふつうのひと', type: 'general' },
  { word: '中手', meaning: 'なかて/てのまんなか', type: 'general' },
  { word: '中耳', meaning: 'ちゅうじ/みみのおく', type: 'general' },
  { word: '中口', meaning: 'なかぐち', type: 'surname' },
  { word: '中金', meaning: 'なかがね', type: 'surname' },

  // ===== 虫 =====
  { word: '虫目', meaning: 'むしめ/むしのめ', type: 'general' },
  { word: '虫気', meaning: 'むしけ/きぶんがわるい', type: 'general' },
  { word: '虫田', meaning: 'むしだ', type: 'surname' },
  { word: '虫川', meaning: 'むしかわ', type: 'surname' },
  { word: '虫山', meaning: 'むしやま', type: 'surname' },

  // ===== 町 =====
  { word: '町中', meaning: 'まちなか/まちのなか', type: 'general' },
  { word: '町人', meaning: 'ちょうにん/まちにすむひと', type: 'general' },
  { word: '町田', meaning: 'まちだ', type: 'surname' },
  { word: '町村', meaning: 'ちょうそん/まちとむら', type: 'general' },
  { word: '町名', meaning: 'ちょうめい/まちのなまえ', type: 'general' },
  { word: '町山', meaning: 'まちやま', type: 'surname' },
  { word: '町川', meaning: 'まちかわ', type: 'surname' },

  // ===== 天 =====
  { word: '天下', meaning: 'てんか/よのなかぜんたい', type: 'general' },
  { word: '天上', meaning: 'てんじょう/そらのうえ', type: 'general' },
  { word: '天女', meaning: 'てんにょ/そらのおんな', type: 'general' },
  { word: '天王', meaning: 'てんのう/そらのおう', type: 'general' },
  { word: '天気', meaning: 'てんき/そらのようす', type: 'general' },
  { word: '天空', meaning: 'てんくう/おおぞら', type: 'general' },
  { word: '天日', meaning: 'てんぴ/たいようのひかり', type: 'general' },
  { word: '天文', meaning: 'てんもん/そらのけんきゅう', type: 'general' },
  { word: '天田', meaning: 'あまだ', type: 'surname' },
  { word: '天川', meaning: 'あまかわ', type: 'surname' },
  { word: '天木', meaning: 'あまき', type: 'surname' },
  { word: '天水', meaning: 'てんすい/あまみず', type: 'general' },
  { word: '天人', meaning: 'てんにん/そらのひと', type: 'general' },
  { word: '天火', meaning: 'てんび/そらのひ', type: 'general' },
  { word: '天山', meaning: 'てんざん/そらにとどくやま', type: 'general' },
  { word: '天中', meaning: 'てんちゅう/そらのまんなか', type: 'general' },
  { word: '天子', meaning: 'てんし/てんのうさま', type: 'general' },

  // ===== 田 =====
  { word: '田中', meaning: 'たなか', type: 'surname' },
  { word: '田村', meaning: 'たむら', type: 'surname' },
  { word: '田口', meaning: 'たぐち', type: 'surname' },
  { word: '田山', meaning: 'たやま', type: 'surname' },
  { word: '田川', meaning: 'たがわ', type: 'surname' },
  { word: '田本', meaning: 'たもと', type: 'surname' },
  { word: '田林', meaning: 'たばやし', type: 'surname' },
  { word: '田子', meaning: 'たご', type: 'surname' },
  { word: '田水', meaning: 'たみず/たのみず', type: 'general' },
  { word: '田土', meaning: 'たつち/たのつち', type: 'general' },
  { word: '田草', meaning: 'たくさ/たのくさ', type: 'general' },
  { word: '田虫', meaning: 'たむし/ひふびょう', type: 'general' },

  // ===== 土 =====
  { word: '土中', meaning: 'どちゅう/つちのなか', type: 'general' },
  { word: '土手', meaning: 'どて/つちをもったもの', type: 'general' },
  { word: '土日', meaning: 'どにち/どようびにちようび', type: 'general' },
  { word: '土木', meaning: 'どぼく/けんせつこうじ', type: 'general' },
  { word: '土田', meaning: 'つちだ', type: 'surname' },
  { word: '土山', meaning: 'つちやま', type: 'surname' },
  { word: '土川', meaning: 'つちかわ', type: 'surname' },
  { word: '土足', meaning: 'どそく/くつをはいたまま', type: 'general' },
  { word: '土気', meaning: 'とけ/つちのにおい', type: 'general' },
  { word: '土人', meaning: 'どじん/むかしのひと', type: 'general' },
  { word: '土石', meaning: 'どせき/つちといし', type: 'general' },

  // ===== 二 =====
  { word: '二人', meaning: 'ふたり', type: 'number' },
  { word: '二日', meaning: 'ふつか', type: 'number' },
  { word: '二月', meaning: 'にがつ', type: 'number' },
  { word: '二本', meaning: 'にほん', type: 'number' },
  { word: '二十', meaning: 'にじゅう', type: 'number' },
  { word: '二三', meaning: 'にさん', type: 'number' },
  { word: '二百', meaning: 'にひゃく', type: 'number' },
  { word: '二千', meaning: 'にせん', type: 'number' },
  { word: '二山', meaning: 'にやま', type: 'surname' },
  { word: '二川', meaning: 'にかわ', type: 'surname' },
  { word: '二村', meaning: 'にむら', type: 'surname' },

  // ===== 日 =====
  { word: '日中', meaning: 'にっちゅう/ひるま', type: 'general' },
  { word: '日本', meaning: 'にほん/わたしたちのくに', type: 'general' },
  { word: '日出', meaning: 'にっしゅつ/ひがのぼる', type: 'general' },
  { word: '日入', meaning: 'にちにゅう/ひがしずむ', type: 'general' },
  { word: '日田', meaning: 'ひた', type: 'surname' },
  { word: '日下', meaning: 'くさか', type: 'surname' },
  { word: '日山', meaning: 'ひやま', type: 'surname' },
  { word: '日月', meaning: 'じつげつ/ひとつき', type: 'general' },
  { word: '日生', meaning: 'ひなせ', type: 'surname' },
  { word: '日立', meaning: 'ひたち', type: 'surname' },
  { word: '日川', meaning: 'ひかわ', type: 'surname' },
  { word: '日村', meaning: 'ひむら', type: 'surname' },
  { word: '日林', meaning: 'ひばやし', type: 'surname' },
  { word: '日水', meaning: 'にっすい/にちすいようび', type: 'general' },
  { word: '日金', meaning: 'にちきん/にちきんようび', type: 'general' },
  { word: '日土', meaning: 'にちど/にちどようび', type: 'general' },
  { word: '日火', meaning: 'にちか/にちかようび', type: 'general' },

  // ===== 入 =====
  { word: '入口', meaning: 'いりぐち/はいるところ', type: 'general' },
  { word: '入学', meaning: 'にゅうがく/がっこうにはいる', type: 'general' },
  { word: '入金', meaning: 'にゅうきん/おかねをいれる', type: 'general' },
  { word: '入手', meaning: 'にゅうしゅ/てにいれる', type: 'general' },
  { word: '入水', meaning: 'にゅうすい/みずにはいる', type: 'general' },
  { word: '入力', meaning: 'にゅうりょく/こんぴゅーたにいれる', type: 'general' },
  { word: '入出', meaning: 'にゅうしゅつ/でたりはいったり', type: 'general' },
  { word: '入山', meaning: 'にゅうざん/やまにはいる', type: 'general' },
  { word: '入日', meaning: 'いりひ/しずむひ', type: 'general' },
  { word: '入火', meaning: 'にゅうか/ひにはいる', type: 'general' },
  { word: '入田', meaning: 'いりた', type: 'surname' },
  { word: '入川', meaning: 'いりかわ', type: 'surname' },

  // ===== 年 =====
  { word: '年中', meaning: 'ねんじゅう/いちねんかん', type: 'general' },
  { word: '年月', meaning: 'ねんげつ/としつき', type: 'general' },
  { word: '年金', meaning: 'ねんきん/おとしよりへのおかね', type: 'general' },
  { word: '年日', meaning: 'ねんじつ/としのひ', type: 'general' },
  { word: '年生', meaning: 'ねんせい/がくねん', type: 'general' },
  { word: '年上', meaning: 'としうえ/じぶんよりうえ', type: 'general' },
  { word: '年下', meaning: 'としした/じぶんよりした', type: 'general' },
  { word: '年男', meaning: 'としおとこ/えとのおとこ', type: 'general' },
  { word: '年女', meaning: 'としおんな/えとのおんな', type: 'general' },
  { word: '年山', meaning: 'としやま', type: 'surname' },
  { word: '年田', meaning: 'としだ', type: 'surname' },
  { word: '年川', meaning: 'としかわ', type: 'surname' },

  // ===== 白 =====
  { word: '白人', meaning: 'はくじん/しろいひふのひと', type: 'general' },
  { word: '白金', meaning: 'はっきん/プラチナ', type: 'general' },
  { word: '白玉', meaning: 'しらたま/しろいたま', type: 'general' },
  { word: '白目', meaning: 'しろめ/めのしろいぶぶん', type: 'general' },
  { word: '白糸', meaning: 'しらいと/しろいいと', type: 'general' },
  { word: '白石', meaning: 'しらいし', type: 'surname' },
  { word: '白川', meaning: 'しらかわ', type: 'surname' },
  { word: '白木', meaning: 'しらき', type: 'surname' },
  { word: '白田', meaning: 'しらた', type: 'surname' },
  { word: '白山', meaning: 'はくさん/しろいやま', type: 'general' },
  { word: '白村', meaning: 'しらむら', type: 'surname' },
  { word: '白中', meaning: 'しらなか', type: 'surname' },
  { word: '白火', meaning: 'しらび/しろいひ', type: 'general' },
  { word: '白水', meaning: 'しろみず/とうめいなみず', type: 'general' },

  // ===== 八 =====
  { word: '八人', meaning: 'はちにん', type: 'number' },
  { word: '八日', meaning: 'ようか', type: 'number' },
  { word: '八月', meaning: 'はちがつ', type: 'number' },
  { word: '八本', meaning: 'はっぽん', type: 'number' },
  { word: '八十', meaning: 'はちじゅう', type: 'number' },
  { word: '八木', meaning: 'やぎ', type: 'surname' },
  { word: '八九', meaning: 'はっく', type: 'number' },
  { word: '八百', meaning: 'はっぴゃく', type: 'number' },
  { word: '八千', meaning: 'はっせん', type: 'number' },
  { word: '八山', meaning: 'やつやま', type: 'surname' },
  { word: '八田', meaning: 'はった', type: 'surname' },
  { word: '八川', meaning: 'やつかわ', type: 'surname' },

  // ===== 百 =====
  { word: '百円', meaning: 'ひゃくえん', type: 'number' },
  { word: '百人', meaning: 'ひゃくにん', type: 'number' },
  { word: '百年', meaning: 'ひゃくねん', type: 'number' },
  { word: '百日', meaning: 'ひゃくにち', type: 'number' },
  { word: '百本', meaning: 'ひゃっぽん', type: 'number' },
  { word: '百花', meaning: 'ひゃっか/たくさんのはな', type: 'general' },
  { word: '百草', meaning: 'ひゃくそう/たくさんのくさ', type: 'general' },
  { word: '百山', meaning: 'ももやま', type: 'surname' },
  { word: '百田', meaning: 'ももた', type: 'surname' },
  { word: '百川', meaning: 'ももかわ', type: 'surname' },
  { word: '百目', meaning: 'ひゃくめ/ひゃくばんめ', type: 'general' },
  { word: '百金', meaning: 'ひゃっきん/ひゃくえん', type: 'general' },

  // ===== 文 =====
  { word: '文中', meaning: 'ぶんちゅう/ぶんしょうのなか', type: 'general' },
  { word: '文字', meaning: 'もじ/かいたことば', type: 'general' },
  { word: '文火', meaning: 'ぶんか/よわいひ', type: 'general' },
  { word: '文金', meaning: 'ぶんきん/おかねのたんい', type: 'general' },
  { word: '文人', meaning: 'ぶんじん/ぶんがくをするひと', type: 'general' },
  { word: '文名', meaning: 'ぶんめい/ぶんがくのなまえ', type: 'general' },
  { word: '文山', meaning: 'ぶんざん/たくさんのぶんしょう', type: 'general' },
  { word: '文田', meaning: 'ふみた', type: 'surname' },
  { word: '文川', meaning: 'ふみかわ', type: 'surname' },

  // ===== 木 =====
  { word: '木立', meaning: 'こだち/きがたっている', type: 'general' },
  { word: '木目', meaning: 'もくめ/きのもよう', type: 'general' },
  { word: '木石', meaning: 'ぼくせき/きといし', type: 'general' },
  { word: '木下', meaning: 'きのした', type: 'surname' },
  { word: '木村', meaning: 'きむら', type: 'surname' },
  { word: '木田', meaning: 'きだ', type: 'surname' },
  { word: '木山', meaning: 'きやま', type: 'surname' },
  { word: '木川', meaning: 'きかわ', type: 'surname' },
  { word: '木中', meaning: 'きなか', type: 'surname' },
  { word: '木本', meaning: 'きもと', type: 'surname' },
  { word: '木口', meaning: 'きぐち/きをきったところ', type: 'general' },
  { word: '木耳', meaning: 'きくらげ/きのこのなかま', type: 'general' },
  { word: '木火', meaning: 'もっか/きとひ', type: 'general' },
  { word: '木水', meaning: 'もくすい/きとみず', type: 'general' },
  { word: '木土', meaning: 'もくど/きとつち', type: 'general' },
  { word: '木金', meaning: 'もっきん/もくようきんよう', type: 'general' },
  { word: '木人', meaning: 'もくじん/きでつくったひと', type: 'general' },

  // ===== 本 =====
  { word: '本人', meaning: 'ほんにん/そのひとじしん', type: 'general' },
  { word: '本名', meaning: 'ほんみょう/ほんとうのなまえ', type: 'general' },
  { word: '本日', meaning: 'ほんじつ/きょう', type: 'general' },
  { word: '本文', meaning: 'ほんぶん/おもなぶんしょう', type: 'general' },
  { word: '本気', meaning: 'ほんき/まじめなきもち', type: 'general' },
  { word: '本田', meaning: 'ほんだ', type: 'surname' },
  { word: '本山', meaning: 'ほんざん・もとやま', type: 'surname' },
  { word: '本村', meaning: 'もとむら', type: 'surname' },
  { word: '本林', meaning: 'もとばやし', type: 'surname' },
  { word: '本中', meaning: 'もとなか', type: 'surname' },
  { word: '本川', meaning: 'もとかわ', type: 'surname' },
  { word: '本木', meaning: 'もとき', type: 'surname' },
  { word: '本年', meaning: 'ほんねん/ことし', type: 'general' },
  { word: '本月', meaning: 'ほんげつ/こんげつ', type: 'general' },
  { word: '本手', meaning: 'ほんて/ただしいやりかた', type: 'general' },
  { word: '本目', meaning: 'ほんめ/〜ばんめ', type: 'general' },
  { word: '本火', meaning: 'ほんか/ほんとうのひ', type: 'general' },
  { word: '本水', meaning: 'ほんすい/ほんとうのみず', type: 'general' },
  { word: '本金', meaning: 'ほんきん/もとのおかね', type: 'general' },

  // ===== 名 =====
  { word: '名人', meaning: 'めいじん/じょうずなひと', type: 'general' },
  { word: '名字', meaning: 'みょうじ/かぞくのなまえ', type: 'general' },
  { word: '名月', meaning: 'めいげつ/きれいなつき', type: 'general' },
  { word: '名目', meaning: 'めいもく/なまえだけ', type: 'general' },
  { word: '名文', meaning: 'めいぶん/すばらしいぶん', type: 'general' },
  { word: '名水', meaning: 'めいすい/おいしいみず', type: 'general' },
  { word: '名山', meaning: 'めいざん/ゆうめいなやま', type: 'general' },
  { word: '名手', meaning: 'めいしゅ/じょうずなひと', type: 'general' },
  { word: '名犬', meaning: 'めいけん/すばらしいいぬ', type: 'general' },
  { word: '名玉', meaning: 'めいぎょく/すばらしいたま', type: 'general' },
  { word: '名石', meaning: 'めいせき/すばらしいいし', type: 'general' },
  { word: '名木', meaning: 'めいぼく/すばらしいき', type: 'general' },
  { word: '名花', meaning: 'めいか/すばらしいはな', type: 'general' },
  { word: '名草', meaning: 'なぐさ/なのあるくさ', type: 'general' },
  { word: '名田', meaning: 'なだ', type: 'surname' },
  { word: '名川', meaning: 'なかわ', type: 'surname' },
  { word: '山名', meaning: 'やまな', type: 'surname' },

  // ===== 目 =====
  { word: '目上', meaning: 'めうえ/じぶんよりうえのひと', type: 'general' },
  { word: '目下', meaning: 'めした/じぶんよりしたのひと', type: 'general' },
  { word: '目玉', meaning: 'めだま/めのたま', type: 'general' },
  { word: '目立', meaning: 'めだつ/よくみえる', type: 'general' },
  { word: '目力', meaning: 'めぢから/めのちから', type: 'general' },
  { word: '目先', meaning: 'めさき/めのまえ', type: 'general' },
  { word: '目白', meaning: 'めじろ/ちいさいとり', type: 'general' },
  { word: '目金', meaning: 'めがね/みるどうぐ', type: 'general' },
  { word: '目出', meaning: 'めで/めでたい', type: 'general' },
  { word: '目山', meaning: 'めやま', type: 'surname' },
  { word: '目田', meaning: 'めだ', type: 'surname' },
  { word: '目川', meaning: 'めかわ', type: 'surname' },

  // ===== 立 =====
  { word: '立入', meaning: 'たちいり/はいること', type: 'general' },
  { word: '立山', meaning: 'たてやま/やまのなまえ', type: 'general' },
  { word: '立川', meaning: 'たちかわ', type: 'surname' },
  { word: '立田', meaning: 'たつた', type: 'surname' },
  { word: '立石', meaning: 'たていし', type: 'surname' },
  { word: '立花', meaning: 'たちばな', type: 'surname' },
  { word: '立木', meaning: 'たちき/たっているき', type: 'general' },
  { word: '立火', meaning: 'たちび/もえているひ', type: 'general' },
  { word: '立水', meaning: 'たちみず/たちどまるみず', type: 'general' },
  { word: '立金', meaning: 'たてきん/たてかえるおかね', type: 'general' },
  { word: '立人', meaning: 'りつじん/たっているひと', type: 'general' },
  { word: '立竹', meaning: 'たちたけ/たっているたけ', type: 'general' },
  { word: '立草', meaning: 'たちくさ/たっているくさ', type: 'general' },

  // ===== 力 =====
  { word: '力山', meaning: 'りきざん/ちからのやま', type: 'general' },
  { word: '力田', meaning: 'りきた', type: 'surname' },
  { word: '力川', meaning: 'りきかわ', type: 'surname' },
  { word: '力石', meaning: 'りきいし/つよいいし', type: 'general' },
  { word: '力人', meaning: 'りきじん/ちからのあるひと', type: 'general' },
  { word: '力足', meaning: 'ちからあし/ちからのあるあし', type: 'general' },
  { word: '力手', meaning: 'ちからて/ちからのあるて', type: 'general' },
  { word: '力火', meaning: 'りきか/つよいひ', type: 'general' },
  { word: '力水', meaning: 'りきすい/つよいみず', type: 'general' },
  { word: '力金', meaning: 'りききん/ちからのおかね', type: 'general' },

  // ===== 林 =====
  { word: '林中', meaning: 'りんちゅう/はやしのなか', type: 'general' },
  { word: '林田', meaning: 'はやしだ', type: 'surname' },
  { word: '林本', meaning: 'はやしもと', type: 'surname' },
  { word: '林山', meaning: 'はやしやま', type: 'surname' },
  { word: '林村', meaning: 'はやしむら', type: 'surname' },
  { word: '林川', meaning: 'はやしかわ', type: 'surname' },
  { word: '林立', meaning: 'りんりつ/たくさんたっている', type: 'general' },
  { word: '林火', meaning: 'りんか/はやしのひ', type: 'general' },

  // ===== 六 =====
  { word: '六人', meaning: 'ろくにん', type: 'number' },
  { word: '六日', meaning: 'むいか', type: 'number' },
  { word: '六月', meaning: 'ろくがつ', type: 'number' },
  { word: '六本', meaning: 'ろっぽん', type: 'number' },
  { word: '六十', meaning: 'ろくじゅう', type: 'number' },
  { word: '六七', meaning: 'ろくしち', type: 'number' },
  { word: '六百', meaning: 'ろっぴゃく', type: 'number' },
  { word: '六千', meaning: 'ろくせん', type: 'number' },

  // ===== 追加エントリー =====
  { word: '足立', meaning: 'あだち/ちめい', type: 'general' },
  { word: '力学', meaning: 'りきがく/ちからのがくもん', type: 'general' },
  { word: '音大', meaning: 'おんだい/おんがくだいがく', type: 'general' },
  { word: '右山', meaning: 'みぎやま/みぎのやま', type: 'general' },
  { word: '王金', meaning: 'おうごん/おうさまのきん', type: 'general' },
  { word: '音火', meaning: 'おんか/おとのひ', type: 'general' },
  { word: '音水', meaning: 'おんすい/みずのおと', type: 'general' },
  { word: '音金', meaning: 'おんきん/かねのおと', type: 'general' },
  { word: '下学', meaning: 'かがく/したでまなぶ', type: 'general' },
  { word: '下出', meaning: 'かしゅつ/したにでる', type: 'general' },
  { word: '火田', meaning: 'かでん/ひのた', type: 'general' },
  { word: '火休', meaning: 'かきゅう/ひをやすめる', type: 'general' },
  { word: '花雨', meaning: 'かう/はなとあめ', type: 'general' },
  { word: '花天', meaning: 'かてん/はなのそら', type: 'general' },
  { word: '花生', meaning: 'かせい/はなをいける', type: 'general' },
  { word: '花文', meaning: 'かもん/はなのもよう', type: 'general' },
  { word: '貝火', meaning: 'かいび/かいのひ', type: 'general' },
  { word: '貝目', meaning: 'かいめ/かいのめ', type: 'general' },
  { word: '学山', meaning: 'がくざん/まなびのやま', type: 'general' },
  { word: '学休', meaning: 'がっきゅう/がっこうをやすむ', type: 'general' },
  { word: '学文', meaning: 'がくぶん/まなびのぶん', type: 'general' },
  { word: '気人', meaning: 'きじん/ふしぎなひと', type: 'general' },
  { word: '気本', meaning: 'きほん/きもちのもと', type: 'general' },
  { word: '気空', meaning: 'きくう/そらのようす', type: 'general' },
  { word: '気天', meaning: 'きてん/てんきのようす', type: 'general' },
  { word: '気土', meaning: 'きど/つちのようす', type: 'general' },
  { word: '気火', meaning: 'きか/ひのようす', type: 'general' },
  { word: '気水', meaning: 'きすい/みずのようす', type: 'general' },
  { word: '休水', meaning: 'きゅうすい/みずをとめる', type: 'general' },
  { word: '玉金', meaning: 'ぎょっきん/たまときん', type: 'general' },
  { word: '玉火', meaning: 'たまび/たまのひ', type: 'general' },
  { word: '玉気', meaning: 'たまき/たまのき', type: 'general' },
  { word: '玉文', meaning: 'ぎょくぶん/すばらしいぶん', type: 'general' },
  { word: '玉目', meaning: 'たまめ/たまのめ', type: 'general' },
  { word: '金白', meaning: 'きんぱく/きんのはく', type: 'general' },
  { word: '金貝', meaning: 'かながい/きんのかい', type: 'general' },
  { word: '金赤', meaning: 'きんあか/きんのあか', type: 'general' },
  { word: '金耳', meaning: 'きんじ/きんのみみ', type: 'general' },
  { word: '空山', meaning: 'くうざん/からっぽのやま', type: 'general' },
  { word: '空人', meaning: 'くうじん/くうちゅうのひと', type: 'general' },
  { word: '空文', meaning: 'くうぶん/からっぽのぶん', type: 'general' },
  { word: '月大', meaning: 'つきおお/おおきなつき', type: 'general' },
  { word: '月天', meaning: 'がってん/わかった', type: 'general' },
  { word: '犬目', meaning: 'いぬめ/いぬのめ', type: 'general' },
  { word: '犬耳', meaning: 'いぬみみ/いぬのみみ', type: 'general' },
  { word: '犬足', meaning: 'いぬあし/いぬのあし', type: 'general' },
  { word: '見人', meaning: 'けんにん/みるひと', type: 'general' },
  { word: '見火', meaning: 'けんか/ひをみる', type: 'general' },
  { word: '見水', meaning: 'けんすい/みずをみる', type: 'general' },
  { word: '見金', meaning: 'けんきん/おかねをみる', type: 'general' },
  { word: '見手', meaning: 'みて/みるひと', type: 'general' },
  { word: '口石', meaning: 'くちいし/くちのいし', type: 'general' },
  { word: '校山', meaning: 'こうざん/がっこうのやま', type: 'general' },
  { word: '校田', meaning: 'こうでん/がっこうのた', type: 'general' },
  { word: '左山', meaning: 'ひだりやま/ひだりのやま', type: 'general' },
  { word: '山玉', meaning: 'やまたま/やまのたま', type: 'general' },
  { word: '山空', meaning: 'やまぞら/やまのそら', type: 'general' },
  { word: '山月', meaning: 'さんげつ/やまのつき', type: 'general' },
  { word: '山見', meaning: 'やまみ', type: 'surname' },
  { word: '山五', meaning: 'やまご/やまの５', type: 'general' },
  { word: '山校', meaning: 'さんこう/やまのがっこう', type: 'general' },
  { word: '山左', meaning: 'やまひだり/やまのひだり', type: 'general' },
  { word: '山右', meaning: 'やまみぎ/やまのみぎ', type: 'general' },
  { word: '山子', meaning: 'やまこ/やまのこ', type: 'general' },
  { word: '山糸', meaning: 'やまいと/やまのいと', type: 'general' },
  { word: '山字', meaning: 'やまじ/やまのかたち', type: 'general' },
  { word: '山耳', meaning: 'やまみみ/やまのみみ', type: 'general' },
  { word: '山出', meaning: 'やまで/やまからでる', type: 'general' },
  { word: '山正', meaning: 'やままさ', type: 'surname' },
  { word: '山生', meaning: 'やまおい/やまにそだつ', type: 'general' },
  { word: '山夕', meaning: 'やまゆう/やまのゆうがた', type: 'general' },
  { word: '山赤', meaning: 'やまあか/やまのあか', type: 'general' },
  { word: '山千', meaning: 'やません/たくさんのやま', type: 'general' },
  { word: '山先', meaning: 'やまさき', type: 'surname' },
  { word: '山早', meaning: 'やまはや', type: 'surname' },
  { word: '山足', meaning: 'やまあし/やまをあるく', type: 'general' },
  { word: '山虫', meaning: 'やまむし/やまのむし', type: 'general' },
  { word: '山町', meaning: 'やままち/やまのまち', type: 'general' },
  { word: '山天', meaning: 'やまてん/やまのそら', type: 'general' },
  { word: '山二', meaning: 'やまに/やまのに', type: 'general' },
  { word: '山入', meaning: 'やまいり/やまにはいる', type: 'general' },
  { word: '山年', meaning: 'やまとし/やまのとし', type: 'general' },
  { word: '山白', meaning: 'やましろ/しろいやま', type: 'general' },
  { word: '山八', meaning: 'やまはち/やまのはち', type: 'general' },
  { word: '山百', meaning: 'やまもも/やまのき', type: 'general' },
  { word: '山文', meaning: 'やまぶん/やまのぶん', type: 'general' },
  { word: '山目', meaning: 'やまめ/やまのさかな', type: 'general' },
  { word: '山力', meaning: 'さんりき/やまのちから', type: 'general' },
  { word: '山気', meaning: 'やまき/やまのくうき', type: 'general' },
  { word: '字火', meaning: 'じか/じのひ', type: 'general' },
  { word: '字中', meaning: 'じちゅう/じのなか', type: 'general' },
  { word: '字金', meaning: 'じきん/じのきん', type: 'general' },
  { word: '字文', meaning: 'じぶん/じとぶん', type: 'general' },
  { word: '耳金', meaning: 'みみがね/みみにつけるもの', type: 'general' },
  { word: '耳口', meaning: 'じこう/みみとくち', type: 'general' },
  { word: '車大', meaning: 'くるまおお/おおきなくるま', type: 'general' },
  { word: '車小', meaning: 'くるまこ/ちいさなくるま', type: 'general' },
  { word: '車火', meaning: 'しゃか/くるまのひ', type: 'general' },
  { word: '車水', meaning: 'しゃすい/くるまとみず', type: 'general' },
  { word: '車金', meaning: 'しゃきん/くるまのおかね', type: 'general' },
  { word: '車人', meaning: 'しゃじん/くるまのひと', type: 'general' },
  { word: '手大', meaning: 'ておお/おおきなて', type: 'general' },
  { word: '手文', meaning: 'てぶん/てでかく', type: 'general' },
  { word: '手目', meaning: 'ため/てのめ', type: 'general' },
  { word: '出人', meaning: 'しゅつにん/でるひと', type: 'general' },
  { word: '女田', meaning: 'おんなだ', type: 'surname' },
  { word: '小文', meaning: 'こもん/ちいさいもじ', type: 'general' },
  { word: '小音', meaning: 'しょうおん/ちいさいおと', type: 'general' },
  { word: '小気', meaning: 'しょうき/よわいき', type: 'general' },
  { word: '小車', meaning: 'こぐるま/ちいさなくるま', type: 'general' },
  { word: '小立', meaning: 'こだて/ちいさくたつ', type: 'general' },
  { word: '小名', meaning: 'こな/ちいさいなまえ', type: 'general' },
  { word: '小王', meaning: 'しょうおう/ちいさいおう', type: 'general' },
  { word: '小力', meaning: 'しょうりき/ちいさいちから', type: 'general' },
  { word: '上出', meaning: 'じょうしゅつ/うえにでる', type: 'general' },
  { word: '上金', meaning: 'じょうきん/うえのきん', type: 'general' },
  { word: '人天', meaning: 'にんてん/ひととてん', type: 'general' },
  { word: '人学', meaning: 'じんがく/ひとのがくもん', type: 'general' },
  { word: '人空', meaning: 'じんくう/ひとのいないそら', type: 'general' },
  { word: '人土', meaning: 'じんど/ひととつち', type: 'general' },
  { word: '人入', meaning: 'じんにゅう/ひとがはいる', type: 'general' },
  { word: '人金', meaning: 'じんきん/ひとのおかね', type: 'general' },
  { word: '人車', meaning: 'じんしゃ/ひとのくるま', type: 'general' },
  { word: '水土', meaning: 'すいど/みずとつち', type: 'general' },
  { word: '水文', meaning: 'すいもん/みずのがくもん', type: 'general' },
  { word: '正山', meaning: 'まさやま', type: 'surname' },
  { word: '正川', meaning: 'まさかわ', type: 'surname' },
  { word: '正村', meaning: 'まさむら', type: 'surname' },
  { word: '正日', meaning: 'せいじつ/ただしいひ', type: 'general' },
  { word: '正火', meaning: 'しょうか/ただしいひ', type: 'general' },
  { word: '正金', meaning: 'しょうきん/ただしいきん', type: 'general' },
  { word: '生人', meaning: 'せいじん/いきているひと', type: 'general' },
  { word: '生火', meaning: 'なまび/なまのひ', type: 'general' },
  { word: '生金', meaning: 'なまがね/ならしていないきん', type: 'general' },
  { word: '生耳', meaning: 'なまみみ/なまのみみ', type: 'general' },
  { word: '生先', meaning: 'うまれさき/うまれたところ', type: 'general' },
  { word: '青金', meaning: 'あおがね/あおいきん', type: 'general' },
  { word: '青赤', meaning: 'あおあか/あおとあか', type: 'general' },
  { word: '夕火', meaning: 'ゆうひ/ゆうがたのひ', type: 'general' },
  { word: '石金', meaning: 'いしがね/いしときん', type: 'general' },
  { word: '石赤', meaning: 'いしあか/あかいいし', type: 'general' },
  { word: '石千', meaning: 'いしせん/たくさんのいし', type: 'general' },
  { word: '石土', meaning: 'いしつち/いしとつち', type: 'general' },
  { word: '石人', meaning: 'せきじん/いしのひと', type: 'general' },
  { word: '石文', meaning: 'せきぶん/いしのぶん', type: 'general' },
  { word: '石気', meaning: 'せっき/いしのき', type: 'general' },
  { word: '赤青', meaning: 'あかあお/あかとあお', type: 'general' },
  { word: '赤水', meaning: 'あかみず/あかいみず', type: 'general' },
  { word: '千火', meaning: 'せんか/たくさんのひ', type: 'general' },
  { word: '川山', meaning: 'かわやま', type: 'surname' },
  { word: '川玉', meaning: 'かわたま/かわのたま', type: 'general' },
  { word: '川金', meaning: 'かわかね/かわのきん', type: 'general' },
  { word: '川空', meaning: 'かわぞら/かわのそら', type: 'general' },
  { word: '川月', meaning: 'かわつき', type: 'surname' },
  { word: '川見', meaning: 'かわみ', type: 'surname' },
  { word: '川子', meaning: 'かわこ', type: 'surname' },
  { word: '川糸', meaning: 'かわいと/かわのいと', type: 'general' },
  { word: '川車', meaning: 'かわぐるま/みずぐるま', type: 'general' },
  { word: '川出', meaning: 'かわで/かわにでる', type: 'general' },
  { word: '川女', meaning: 'かわめ/かわのおんな', type: 'general' },
  { word: '川人', meaning: 'かわと', type: 'surname' },
  { word: '川正', meaning: 'かわまさ', type: 'surname' },
  { word: '川生', meaning: 'かわお/かわのいきもの', type: 'general' },
  { word: '川夕', meaning: 'かわゆう/かわのゆうがた', type: 'general' },
  { word: '川千', meaning: 'かわせん/たくさんのかわ', type: 'general' },
  { word: '川先', meaning: 'かわさき', type: 'surname' },
  { word: '川足', meaning: 'かわあし/かわをあるく', type: 'general' },
  { word: '川男', meaning: 'かわお/かわのおとこ', type: 'general' },
  { word: '川竹', meaning: 'かわたけ', type: 'surname' },
  { word: '川町', meaning: 'かわまち/かわのまち', type: 'general' },
  { word: '川二', meaning: 'かわに/かわの２', type: 'general' },
  { word: '川日', meaning: 'かわひ/かわのひ', type: 'general' },
  { word: '川入', meaning: 'かわいり/かわにはいる', type: 'general' },
  { word: '川年', meaning: 'かわとし/かわのとし', type: 'general' },
  { word: '川八', meaning: 'かわはち/かわの８', type: 'general' },
  { word: '川百', meaning: 'かわもも/たくさんのかわ', type: 'general' },
  { word: '川文', meaning: 'かわぶん/かわのぶん', type: 'general' },
  { word: '川木', meaning: 'かわき', type: 'surname' },
  { word: '川名', meaning: 'かわな', type: 'surname' },
  { word: '川目', meaning: 'かわめ', type: 'surname' },
  { word: '川力', meaning: 'かわりき/かわのちから', type: 'general' },
  { word: '先火', meaning: 'せんか/さきのひ', type: 'general' },
  { word: '早火', meaning: 'はやび/はやいひ', type: 'general' },
  { word: '早水', meaning: 'はやみず/はやいみず', type: 'general' },
  { word: '草水', meaning: 'くさみず/くさのみず', type: 'general' },
  { word: '草文', meaning: 'そうぶん/くさのぶん', type: 'general' },
  { word: '足大', meaning: 'あしおお/おおきなあし', type: 'general' },
  { word: '村玉', meaning: 'むらたま/むらのたま', type: 'general' },
  { word: '村金', meaning: 'むらかね/むらのきん', type: 'general' },
  { word: '村空', meaning: 'むらぞら/むらのそら', type: 'general' },
  { word: '村月', meaning: 'むらつき', type: 'surname' },
  { word: '村糸', meaning: 'むらいと/むらのいと', type: 'general' },
  { word: '村手', meaning: 'むらて/むらのて', type: 'general' },
  { word: '村水', meaning: 'むらみず/むらのみず', type: 'general' },
  { word: '村正', meaning: 'むらまさ', type: 'surname' },
  { word: '村生', meaning: 'むらお/むらのいきもの', type: 'general' },
  { word: '村石', meaning: 'むらいし', type: 'surname' },
  { word: '村赤', meaning: 'むらあか/むらのあか', type: 'general' },
  { word: '村千', meaning: 'むらせん/たくさんのむら', type: 'general' },
  { word: '村大', meaning: 'むらおお/おおきなむら', type: 'general' },
  { word: '村町', meaning: 'むらまち/むらのまち', type: 'general' },
  { word: '村二', meaning: 'むらに/むらの２', type: 'general' },
  { word: '村日', meaning: 'むらひ/むらのひ', type: 'general' },
  { word: '村白', meaning: 'むらしろ', type: 'surname' },
  { word: '村火', meaning: 'むらび/むらのひ', type: 'general' },
  { word: '大音', meaning: 'おおおと/おおきなおと', type: 'general' },
  { word: '大車', meaning: 'おおぐるま/おおきなくるま', type: 'general' },
  { word: '大年', meaning: 'おおとし/おおみそか', type: 'general' },
  { word: '大出', meaning: 'おおで/おおきくでる', type: 'general' },
  { word: '大立', meaning: 'おおだて/おおきくたつ', type: 'general' },
  { word: '大天', meaning: 'だいてん/おおきなそら', type: 'general' },
  { word: '男田', meaning: 'おだ', type: 'surname' },
  { word: '男川', meaning: 'おがわ', type: 'surname' },
  { word: '竹文', meaning: 'ちくぶん/たけのぶん', type: 'general' },
  { word: '中校', meaning: 'ちゅうこう/ちゅうがっこう', type: 'general' },
  { word: '中白', meaning: 'なかしろ', type: 'surname' },
  { word: '中木', meaning: 'なかき', type: 'surname' },
  { word: '中足', meaning: 'なかあし/まんなかのあし', type: 'general' },
  { word: '虫火', meaning: 'むしび/むしのひ', type: 'general' },
  { word: '虫水', meaning: 'むしみず/むしのみず', type: 'general' },
  { word: '町火', meaning: 'まちび/まちのひ', type: 'general' },
  { word: '天花', meaning: 'てんか/そらのはな', type: 'general' },
  { word: '天金', meaning: 'てんきん/そらのきん', type: 'general' },
  { word: '天竹', meaning: 'あまたけ', type: 'surname' },
  { word: '天手', meaning: 'あまて/そらのて', type: 'general' },
  { word: '田石', meaning: 'たいし', type: 'surname' },
  { word: '田玉', meaning: 'たたま/たのたま', type: 'general' },
  { word: '田空', meaning: 'たぞら/たのそら', type: 'general' },
  { word: '田見', meaning: 'たみ', type: 'surname' },
  { word: '田五', meaning: 'たご/たの５', type: 'general' },
  { word: '田校', meaning: 'でんこう/たのがっこう', type: 'general' },
  { word: '田糸', meaning: 'たいと/たのいと', type: 'general' },
  { word: '田字', meaning: 'たじ/たのかたち', type: 'general' },
  { word: '田耳', meaning: 'たみみ/たのみみ', type: 'general' },
  { word: '田車', meaning: 'たぐるま/たのくるま', type: 'general' },
  { word: '田手', meaning: 'たて/たのて', type: 'general' },
  { word: '田出', meaning: 'たで/たにでる', type: 'general' },
  { word: '田女', meaning: 'たおんな/たのおんな', type: 'general' },
  { word: '田人', meaning: 'たびと/たのひと', type: 'general' },
  { word: '田正', meaning: 'たまさ', type: 'surname' },
  { word: '田夕', meaning: 'たゆう/たのゆうがた', type: 'general' },
  { word: '田先', meaning: 'たさき', type: 'surname' },
  { word: '田早', meaning: 'たはや', type: 'surname' },
  { word: '田足', meaning: 'たあし/たをあるく', type: 'general' },
  { word: '田男', meaning: 'たお/たのおとこ', type: 'general' },
  { word: '田入', meaning: 'たいり/たにはいる', type: 'general' },
  { word: '田年', meaning: 'たとし/たのとし', type: 'general' },
  { word: '田八', meaning: 'たはち/たの８', type: 'general' },
  { word: '田百', meaning: 'たもも/たくさんのた', type: 'general' },
  { word: '田文', meaning: 'たぶん/おそらく', type: 'general' },
  { word: '田名', meaning: 'たな', type: 'surname' },
  { word: '田目', meaning: 'ため/たんぼのめ', type: 'general' },
  { word: '田力', meaning: 'たりき/たんぼのちから', type: 'general' },
  { word: '土金', meaning: 'どきん/どようきんよう', type: 'general' },
  { word: '土火', meaning: 'どか/つちとひ', type: 'general' },
  { word: '土水', meaning: 'どすい/つちとみず', type: 'general' },
  { word: '日木', meaning: 'にちもく/にちようもくよう', type: 'general' },
  { word: '日休', meaning: 'にちきゅう/にちようきゅうじつ', type: 'general' },
  { word: '日大', meaning: 'にちだい/にほんだいがく', type: 'general' },
  { word: '日天', meaning: 'にってん/たいよう', type: 'general' },
  { word: '年大', meaning: 'としおお/おおきなとし', type: 'general' },
  { word: '白青', meaning: 'しろあお/しろとあお', type: 'general' },
  { word: '白赤', meaning: 'しろあか/しろとあか', type: 'general' },
  { word: '百火', meaning: 'ひゃっか/たくさんのひ', type: 'general' },
  { word: '百手', meaning: 'ひゃくて/たくさんのて', type: 'general' },
  { word: '文目', meaning: 'ふみめ/ぶんのめ', type: 'general' },
  { word: '木空', meaning: 'きくう/きとそら', type: 'general' },
  { word: '木手', meaning: 'きて/きのて', type: 'general' },
  { word: '本石', meaning: 'もといし', type: 'surname' },
  { word: '本大', meaning: 'もとおお/もとのおおきさ', type: 'general' },
  { word: '名火', meaning: 'めいか/ゆうめいなひ', type: 'general' },
  { word: '立王', meaning: 'りつおう/たったおう', type: 'general' },
  { word: '林金', meaning: 'はやしかね', type: 'surname' },
  { word: '林石', meaning: 'はやしいし', type: 'surname' },
  { word: '林日', meaning: 'はやしひ', type: 'surname' },

  // ===== 数字+単位（追加分） =====
  { word: '二円', meaning: 'にえん', type: 'number' },
  { word: '二年', meaning: 'にねん', type: 'number' },
  { word: '二名', meaning: 'にめい', type: 'number' },
  { word: '二目', meaning: 'ふため', type: 'number' },
  { word: '二手', meaning: 'ふたて', type: 'number' },
  { word: '二口', meaning: 'ふたくち', type: 'number' },
  { word: '二文', meaning: 'にもん', type: 'number' },
  { word: '二石', meaning: 'にこく', type: 'number' },
  { word: '三円', meaning: 'さんえん', type: 'number' },
  { word: '三年', meaning: 'さんねん', type: 'number' },
  { word: '三名', meaning: 'さんめい', type: 'number' },
  { word: '三目', meaning: 'みため', type: 'number' },
  { word: '三手', meaning: 'みて', type: 'number' },
  { word: '三口', meaning: 'みくち', type: 'number' },
  { word: '三文', meaning: 'さんもん', type: 'number' },
  { word: '三石', meaning: 'さんごく', type: 'number' },
  { word: '四円', meaning: 'よえん', type: 'number' },
  { word: '四年', meaning: 'よねん', type: 'number' },
  { word: '四名', meaning: 'よんめい', type: 'number' },
  { word: '四目', meaning: 'よんめ', type: 'number' },
  { word: '四手', meaning: 'よて', type: 'number' },
  { word: '四口', meaning: 'よくち', type: 'number' },
  { word: '四文', meaning: 'よんもん', type: 'number' },
  { word: '四石', meaning: 'よんこく', type: 'number' },
  { word: '五年', meaning: 'ごねん', type: 'number' },
  { word: '五名', meaning: 'ごめい', type: 'number' },
  { word: '五目', meaning: 'ごめ', type: 'number' },
  { word: '五手', meaning: 'ごて', type: 'number' },
  { word: '五口', meaning: 'ごくち', type: 'number' },
  { word: '五文', meaning: 'ごもん', type: 'number' },
  { word: '五石', meaning: 'ごこく', type: 'number' },
  { word: '六円', meaning: 'ろくえん', type: 'number' },
  { word: '六年', meaning: 'ろくねん', type: 'number' },
  { word: '六名', meaning: 'ろくめい', type: 'number' },
  { word: '六目', meaning: 'ろくめ', type: 'number' },
  { word: '六手', meaning: 'ろくて', type: 'number' },
  { word: '六口', meaning: 'ろっくち', type: 'number' },
  { word: '六文', meaning: 'ろくもん', type: 'number' },
  { word: '六石', meaning: 'ろっこく', type: 'number' },
  { word: '七円', meaning: 'ななえん', type: 'number' },
  { word: '七年', meaning: 'ななねん', type: 'number' },
  { word: '七本', meaning: 'ななほん', type: 'number' },
  { word: '七名', meaning: 'しちめい', type: 'number' },
  { word: '七目', meaning: 'ななめ', type: 'number' },
  { word: '七手', meaning: 'ななて', type: 'number' },
  { word: '七口', meaning: 'ななくち', type: 'number' },
  { word: '七文', meaning: 'ななもん', type: 'number' },
  { word: '七石', meaning: 'ななこく', type: 'number' },
  { word: '八円', meaning: 'はちえん', type: 'number' },
  { word: '八年', meaning: 'はちねん', type: 'number' },
  { word: '八名', meaning: 'はちめい', type: 'number' },
  { word: '八目', meaning: 'はちめ', type: 'number' },
  { word: '八手', meaning: 'はって', type: 'number' },
  { word: '八口', meaning: 'はちくち', type: 'number' },
  { word: '八文', meaning: 'はちもん', type: 'number' },
  { word: '八石', meaning: 'はっこく', type: 'number' },
  { word: '九円', meaning: 'きゅうえん', type: 'number' },
  { word: '九年', meaning: 'きゅうねん', type: 'number' },
  { word: '九本', meaning: 'きゅうほん', type: 'number' },
  { word: '九名', meaning: 'きゅうめい', type: 'number' },
  { word: '九目', meaning: 'きゅうめ', type: 'number' },
  { word: '九手', meaning: 'きゅうて', type: 'number' },
  { word: '九口', meaning: 'きゅうくち', type: 'number' },
  { word: '九文', meaning: 'きゅうもん', type: 'number' },
  { word: '九石', meaning: 'きゅうこく', type: 'number' },
  { word: '十年', meaning: 'じゅうねん', type: 'number' },
  { word: '十名', meaning: 'じゅうめい', type: 'number' },
  { word: '十目', meaning: 'じゅうめ', type: 'number' },
  { word: '十手', meaning: 'じゅって', type: 'number' },
  { word: '十口', meaning: 'じゅっくち', type: 'number' },
  { word: '十文', meaning: 'じゅうもん', type: 'number' },
  { word: '十石', meaning: 'じゅっこく', type: 'number' },
  { word: '百月', meaning: 'ひゃくげつ', type: 'number' },
  { word: '百名', meaning: 'ひゃくめい', type: 'number' },
  { word: '百口', meaning: 'ひゃっくち', type: 'number' },
  { word: '百文', meaning: 'ひゃくもん', type: 'number' },
  { word: '百石', meaning: 'ひゃっこく', type: 'number' },
  { word: '千月', meaning: 'せんげつ', type: 'number' },
  { word: '千名', meaning: 'せんめい', type: 'number' },
  { word: '千目', meaning: 'せんめ', type: 'number' },
  { word: '千口', meaning: 'せんくち', type: 'number' },
  { word: '千文', meaning: 'せんもん', type: 'number' },
]
