// 80×79の全組み合わせの意味調査データベース
// ジャンル: general(一般), surname(苗字), number(数量), none(意味なし)

export type JukugoEntry = {
  word: string
  meaning: string
  type: 'general' | 'surname' | 'number' | 'none'
}

// 意味のある熟語のみを記載（意味なしは省略）
export const JUKUGO_DATABASE: JukugoEntry[] = [
  // ========== 一 ==========
  { word: '一円', meaning: 'いちえん', type: 'number' },
  { word: '一下', meaning: 'いっか（一度に）', type: 'general' },
  { word: '一気', meaning: 'いっき', type: 'general' },
  { word: '一休', meaning: 'ひとやすみ', type: 'general' },
  { word: '一月', meaning: 'いちがつ', type: 'number' },
  { word: '一見', meaning: 'いっけん', type: 'general' },
  { word: '一口', meaning: 'ひとくち', type: 'number' },
  { word: '一山', meaning: 'ひとやま', type: 'general' },
  { word: '一手', meaning: 'ひとて', type: 'number' },
  { word: '一人', meaning: 'ひとり', type: 'number' },
  { word: '一生', meaning: 'いっしょう', type: 'number' },
  { word: '一石', meaning: 'いっせき', type: 'general' },
  { word: '一千', meaning: 'いっせん', type: 'number' },
  { word: '一村', meaning: 'いっそん', type: 'general' },
  { word: '一大', meaning: 'いちだい', type: 'general' },
  { word: '一中', meaning: 'いっちゅう', type: 'general' },
  { word: '一天', meaning: 'いってん', type: 'general' },
  { word: '一日', meaning: 'ついたち、いちにち', type: 'number' },
  { word: '一入', meaning: 'ひとしお', type: 'general' },
  { word: '一年', meaning: 'いちねん', type: 'number' },
  { word: '一白', meaning: 'いっぱく', type: 'general' },
  { word: '一八', meaning: 'いっぱち', type: 'number' },
  { word: '一百', meaning: 'いっぴゃく', type: 'number' },
  { word: '一文', meaning: 'いちもん', type: 'number' },
  { word: '一本', meaning: 'いっぽん', type: 'number' },
  { word: '一名', meaning: 'いちめい', type: 'number' },
  { word: '一目', meaning: 'ひとめ', type: 'number' },
  { word: '一立', meaning: 'いちりつ', type: 'general' },
  { word: '一力', meaning: 'いちりき', type: 'general' },
  { word: '一六', meaning: 'いちろく', type: 'number' },

  // ========== 右 ==========
  { word: '右手', meaning: 'みぎて', type: 'general' },
  { word: '右足', meaning: 'みぎあし', type: 'general' },
  { word: '右目', meaning: 'みぎめ', type: 'general' },
  { word: '右耳', meaning: 'みぎみみ', type: 'general' },
  { word: '右左', meaning: 'みぎひだり', type: 'general' },

  // ========== 雨 ==========
  { word: '雨音', meaning: 'あまおと', type: 'general' },
  { word: '雨雲', meaning: 'あまぐも', type: 'general' },
  { word: '雨空', meaning: 'あまぞら', type: 'general' },
  { word: '雨水', meaning: 'あまみず', type: 'general' },
  { word: '雨天', meaning: 'うてん', type: 'general' },
  { word: '雨中', meaning: 'うちゅう', type: 'general' },

  // ========== 円 ==========
  { word: '円玉', meaning: 'えんだま', type: 'general' },
  { word: '円山', meaning: 'まるやま', type: 'surname' },

  // ========== 王 ==========
  { word: '王子', meaning: 'おうじ', type: 'general' },
  { word: '王女', meaning: 'おうじょ', type: 'general' },
  { word: '王手', meaning: 'おうて', type: 'general' },
  { word: '王金', meaning: 'おうごん（黄金の当て字）', type: 'general' },

  // ========== 音 ==========
  { word: '音楽', meaning: 'おんがく', type: 'general' },
  { word: '音声', meaning: 'おんせい', type: 'general' },

  // ========== 下 ==========
  { word: '下火', meaning: 'したび', type: 'general' },
  { word: '下学', meaning: 'かがく', type: 'general' },
  { word: '下校', meaning: 'げこう', type: 'general' },
  { word: '下山', meaning: 'げざん', type: 'general' },
  { word: '下車', meaning: 'げしゃ', type: 'general' },
  { word: '下手', meaning: 'へた', type: 'general' },
  { word: '下水', meaning: 'げすい', type: 'general' },
  { word: '下足', meaning: 'げそく', type: 'general' },
  { word: '下田', meaning: 'しもだ', type: 'surname' },
  { word: '下町', meaning: 'したまち', type: 'general' },
  { word: '下人', meaning: 'げにん', type: 'general' },
  { word: '下目', meaning: 'しため', type: 'general' },

  // ========== 火 ==========
  { word: '火気', meaning: 'かき', type: 'general' },
  { word: '火口', meaning: 'かこう', type: 'general' },
  { word: '火山', meaning: 'かざん', type: 'general' },
  { word: '火中', meaning: 'かちゅう', type: 'general' },
  { word: '火田', meaning: 'かでん', type: 'general' },
  { word: '火花', meaning: 'ひばな', type: 'general' },
  { word: '火力', meaning: 'かりょく', type: 'general' },

  // ========== 花 ==========
  { word: '花火', meaning: 'はなび', type: 'general' },
  { word: '花見', meaning: 'はなみ', type: 'general' },
  { word: '花木', meaning: 'かぼく', type: 'general' },
  { word: '花田', meaning: 'はなだ', type: 'surname' },
  { word: '花山', meaning: 'かざん', type: 'surname' },

  // ========== 貝 ==========
  // 貝を使った一般的な熟語は少ない

  // ========== 学 ==========
  { word: '学生', meaning: 'がくせい', type: 'general' },
  { word: '学校', meaning: 'がっこう', type: 'general' },
  { word: '学年', meaning: 'がくねん', type: 'general' },
  { word: '学力', meaning: 'がくりょく', type: 'general' },
  { word: '学名', meaning: 'がくめい', type: 'general' },

  // ========== 気 ==========
  { word: '気力', meaning: 'きりょく', type: 'general' },
  { word: '気休', meaning: 'きやすめ', type: 'general' },
  { word: '気立', meaning: 'きだて', type: 'general' },

  // ========== 九 ==========
  { word: '九人', meaning: 'きゅうにん', type: 'number' },
  { word: '九日', meaning: 'ここのか', type: 'number' },
  { word: '九月', meaning: 'くがつ', type: 'number' },
  { word: '九十', meaning: 'きゅうじゅう', type: 'number' },
  { word: '九州', meaning: 'きゅうしゅう', type: 'general' },

  // ========== 休 ==========
  { word: '休火', meaning: 'きゅうか（休火山）', type: 'general' },
  { word: '休校', meaning: 'きゅうこう', type: 'general' },
  { word: '休日', meaning: 'きゅうじつ', type: 'general' },

  // ========== 玉 ==========
  { word: '玉石', meaning: 'ぎょくせき', type: 'general' },
  { word: '玉入', meaning: 'たまいれ', type: 'general' },
  { word: '玉川', meaning: 'たまがわ', type: 'surname' },
  { word: '玉田', meaning: 'たまだ', type: 'surname' },
  { word: '玉木', meaning: 'たまき', type: 'surname' },

  // ========== 金 ==========
  { word: '金玉', meaning: 'きんぎょく', type: 'general' },
  { word: '金山', meaning: 'きんざん', type: 'general' },
  { word: '金子', meaning: 'かねこ', type: 'surname' },
  { word: '金森', meaning: 'かなもり', type: 'surname' },
  { word: '金田', meaning: 'かねだ', type: 'surname' },
  { word: '金本', meaning: 'かねもと', type: 'surname' },
  { word: '金目', meaning: 'かねめ', type: 'general' },
  { word: '金力', meaning: 'きんりょく', type: 'general' },

  // ========== 空 ==========
  { word: '空気', meaning: 'くうき', type: 'general' },
  { word: '空車', meaning: 'くうしゃ', type: 'general' },
  { word: '空中', meaning: 'くうちゅう', type: 'general' },
  { word: '空白', meaning: 'くうはく', type: 'general' },
  { word: '空手', meaning: 'からて', type: 'general' },

  // ========== 月 ==========
  { word: '月火', meaning: 'げっか（月曜火曜）', type: 'general' },
  { word: '月金', meaning: 'げっきん（月曜金曜）', type: 'general' },
  { word: '月見', meaning: 'つきみ', type: 'general' },
  { word: '月日', meaning: 'つきひ', type: 'general' },
  { word: '月田', meaning: 'つきた', type: 'surname' },

  // ========== 犬 ==========
  // 犬を先頭にした熟語は少ない

  // ========== 見 ==========
  { word: '見学', meaning: 'けんがく', type: 'general' },
  { word: '見出', meaning: 'みだし', type: 'general' },
  { word: '見本', meaning: 'みほん', type: 'general' },

  // ========== 五 ==========
  { word: '五円', meaning: 'ごえん', type: 'number' },
  { word: '五月', meaning: 'ごがつ', type: 'number' },
  { word: '五人', meaning: 'ごにん', type: 'number' },
  { word: '五十', meaning: 'ごじゅう', type: 'number' },
  { word: '五日', meaning: 'いつか', type: 'number' },
  { word: '五本', meaning: 'ごほん', type: 'number' },
  { word: '五木', meaning: 'いつき', type: 'surname' },

  // ========== 口 ==========
  { word: '口火', meaning: 'くちび', type: 'general' },
  { word: '口車', meaning: 'くちぐるま', type: 'general' },
  { word: '口下手', meaning: 'くちべた', type: 'general' },

  // ========== 校 ==========
  { word: '校正', meaning: 'こうせい', type: 'general' },
  { word: '校長', meaning: 'こうちょう', type: 'general' },

  // ========== 左 ==========
  { word: '左右', meaning: 'さゆう', type: 'general' },
  { word: '左手', meaning: 'ひだりて', type: 'general' },
  { word: '左足', meaning: 'ひだりあし', type: 'general' },
  { word: '左目', meaning: 'ひだりめ', type: 'general' },
  { word: '左耳', meaning: 'ひだりみみ', type: 'general' },

  // ========== 三 ==========
  { word: '三月', meaning: 'さんがつ', type: 'number' },
  { word: '三人', meaning: 'さんにん', type: 'number' },
  { word: '三十', meaning: 'さんじゅう', type: 'number' },
  { word: '三日', meaning: 'みっか', type: 'number' },
  { word: '三本', meaning: 'さんぼん', type: 'number' },
  { word: '三木', meaning: 'みき', type: 'surname' },

  // ========== 山 ==========
  { word: '山火', meaning: 'やまび', type: 'general' },
  { word: '山下', meaning: 'やました', type: 'surname' },
  { word: '山口', meaning: 'やまぐち', type: 'surname' },
  { word: '山上', meaning: 'やまがみ', type: 'surname' },
  { word: '山川', meaning: 'やまかわ', type: 'general' },
  { word: '山村', meaning: 'さんそん', type: 'general' },
  { word: '山中', meaning: 'さんちゅう', type: 'general' },
  { word: '山田', meaning: 'やまだ', type: 'surname' },
  { word: '山本', meaning: 'やまもと', type: 'surname' },
  { word: '山林', meaning: 'さんりん', type: 'general' },

  // ========== 子 ==========
  { word: '子犬', meaning: 'こいぬ', type: 'general' },
  { word: '子女', meaning: 'しじょ', type: 'general' },

  // ========== 四 ==========
  { word: '四月', meaning: 'しがつ', type: 'number' },
  { word: '四人', meaning: 'よにん', type: 'number' },
  { word: '四十', meaning: 'よんじゅう', type: 'number' },
  { word: '四日', meaning: 'よっか', type: 'number' },
  { word: '四本', meaning: 'よんほん', type: 'number' },

  // ========== 糸 ==========
  { word: '糸口', meaning: 'いとぐち', type: 'general' },
  { word: '糸目', meaning: 'いとめ', type: 'general' },

  // ========== 字 ==========
  { word: '字名', meaning: 'あざな', type: 'general' },

  // ========== 耳 ==========
  { word: '耳目', meaning: 'じもく', type: 'general' },

  // ========== 七 ==========
  { word: '七月', meaning: 'しちがつ', type: 'number' },
  { word: '七人', meaning: 'しちにん', type: 'number' },
  { word: '七十', meaning: 'ななじゅう', type: 'number' },
  { word: '七日', meaning: 'なのか', type: 'number' },

  // ========== 車 ==========
  { word: '車中', meaning: 'しゃちゅう', type: 'general' },

  // ========== 手 ==========
  { word: '手下', meaning: 'てした', type: 'general' },
  { word: '手先', meaning: 'てさき', type: 'general' },
  { word: '手足', meaning: 'てあし', type: 'general' },
  { word: '手中', meaning: 'しゅちゅう', type: 'general' },
  { word: '手入', meaning: 'ていれ', type: 'general' },
  { word: '手本', meaning: 'てほん', type: 'general' },

  // ========== 十 ==========
  { word: '十円', meaning: 'じゅうえん', type: 'number' },
  { word: '十月', meaning: 'じゅうがつ', type: 'number' },
  { word: '十字', meaning: 'じゅうじ', type: 'number' },
  { word: '十人', meaning: 'じゅうにん', type: 'number' },
  { word: '十中', meaning: 'じゅっちゅう', type: 'general' },
  { word: '十日', meaning: 'とおか', type: 'number' },
  { word: '十本', meaning: 'じゅっぽん', type: 'number' },

  // ========== 出 ==========
  { word: '出火', meaning: 'しゅっか', type: 'general' },
  { word: '出金', meaning: 'しゅっきん', type: 'general' },
  { word: '出口', meaning: 'でぐち', type: 'general' },
  { word: '出生', meaning: 'しゅっせい', type: 'general' },
  { word: '出足', meaning: 'であし', type: 'general' },
  { word: '出入', meaning: 'でいり', type: 'general' },
  { word: '出力', meaning: 'しゅつりょく', type: 'general' },
  { word: '出目', meaning: 'でめ', type: 'general' },

  // ========== 女 ==========
  { word: '女王', meaning: 'じょおう', type: 'general' },
  { word: '女子', meaning: 'じょし', type: 'general' },

  // ========== 小 ==========
  { word: '小雨', meaning: 'こさめ', type: 'general' },
  { word: '小学', meaning: 'しょうがく', type: 'general' },
  { word: '小休', meaning: 'しょうきゅう', type: 'general' },
  { word: '小金', meaning: 'こがね', type: 'general' },
  { word: '小犬', meaning: 'こいぬ', type: 'general' },
  { word: '小火', meaning: 'ぼや', type: 'general' },
  { word: '小石', meaning: 'こいし', type: 'general' },
  { word: '小川', meaning: 'おがわ', type: 'surname' },
  { word: '小田', meaning: 'おだ', type: 'surname' },
  { word: '小手', meaning: 'こて', type: 'general' },
  { word: '小人', meaning: 'しょうにん・こびと', type: 'general' },
  { word: '小文', meaning: 'こもん', type: 'general' },
  { word: '小木', meaning: 'こぎ', type: 'surname' },
  { word: '小山', meaning: 'こやま', type: 'surname' },
  { word: '小林', meaning: 'こばやし', type: 'surname' },

  // ========== 上 ==========
  { word: '上下', meaning: 'じょうげ', type: 'general' },
  { word: '上気', meaning: 'じょうき', type: 'general' },
  { word: '上手', meaning: 'じょうず', type: 'general' },
  { word: '上田', meaning: 'うえだ', type: 'surname' },
  { word: '上山', meaning: 'うえやま', type: 'surname' },

  // ========== 森 ==========
  { word: '森川', meaning: 'もりかわ', type: 'surname' },
  { word: '森山', meaning: 'もりやま', type: 'surname' },
  { word: '森田', meaning: 'もりた', type: 'surname' },
  { word: '森中', meaning: 'もりなか', type: 'surname' },
  { word: '森本', meaning: 'もりもと', type: 'surname' },
  { word: '森林', meaning: 'しんりん', type: 'general' },

  // ========== 人 ==========
  { word: '人気', meaning: 'にんき', type: 'general' },
  { word: '人口', meaning: 'じんこう', type: 'general' },
  { word: '人生', meaning: 'じんせい', type: 'general' },
  { word: '人手', meaning: 'ひとで', type: 'general' },
  { word: '人名', meaning: 'じんめい', type: 'general' },
  { word: '人目', meaning: 'ひとめ', type: 'general' },
  { word: '人力', meaning: 'じんりき', type: 'general' },

  // ========== 水 ==========
  { word: '水気', meaning: 'みずけ', type: 'general' },
  { word: '水金', meaning: 'すいきん（水曜金曜）', type: 'general' },
  { word: '水玉', meaning: 'みずたま', type: 'general' },
  { word: '水口', meaning: 'みなくち', type: 'surname' },
  { word: '水車', meaning: 'すいしゃ', type: 'general' },
  { word: '水草', meaning: 'みずくさ', type: 'general' },
  { word: '水川', meaning: 'みずかわ', type: 'surname' },
  { word: '水中', meaning: 'すいちゅう', type: 'general' },
  { word: '水田', meaning: 'すいでん', type: 'general' },
  { word: '水虫', meaning: 'みずむし', type: 'general' },
  { word: '水本', meaning: 'みずもと', type: 'surname' },
  { word: '水力', meaning: 'すいりょく', type: 'general' },

  // ========== 正 ==========
  { word: '正気', meaning: 'しょうき', type: 'general' },
  { word: '正月', meaning: 'しょうがつ', type: 'general' },
  { word: '正文', meaning: 'せいぶん', type: 'general' },
  { word: '正本', meaning: 'せいほん', type: 'general' },
  { word: '正木', meaning: 'まさき', type: 'surname' },
  { word: '正目', meaning: 'まさめ', type: 'general' },

  // ========== 生 ==========
  { word: '生花', meaning: 'せいか・いけばな', type: 'general' },
  { word: '生気', meaning: 'せいき', type: 'general' },
  { word: '生水', meaning: 'なまみず', type: 'general' },
  { word: '生田', meaning: 'いくた', type: 'surname' },
  { word: '生日', meaning: 'せいじつ', type: 'general' },
  { word: '生年', meaning: 'せいねん', type: 'general' },

  // ========== 青 ==========
  { word: '青空', meaning: 'あおぞら', type: 'general' },
  { word: '青草', meaning: 'あおくさ', type: 'general' },
  { word: '青竹', meaning: 'あおだけ', type: 'general' },
  { word: '青虫', meaning: 'あおむし', type: 'general' },
  { word: '青田', meaning: 'あおた', type: 'surname' },
  { word: '青年', meaning: 'せいねん', type: 'general' },
  { word: '青木', meaning: 'あおき', type: 'surname' },
  { word: '青山', meaning: 'あおやま', type: 'surname' },

  // ========== 夕 ==========
  { word: '夕日', meaning: 'ゆうひ', type: 'general' },
  { word: '夕立', meaning: 'ゆうだち', type: 'general' },

  // ========== 石 ==========
  { word: '石川', meaning: 'いしかわ', type: 'surname' },
  { word: '石山', meaning: 'いしやま', type: 'surname' },
  { word: '石田', meaning: 'いしだ', type: 'surname' },

  // ========== 赤 ==========
  { word: '赤字', meaning: 'あかじ', type: 'general' },
  { word: '赤川', meaning: 'あかがわ', type: 'surname' },
  { word: '赤田', meaning: 'あかだ', type: 'surname' },
  { word: '赤木', meaning: 'あかぎ', type: 'surname' },

  // ========== 千 ==========
  { word: '千円', meaning: 'せんえん', type: 'number' },
  { word: '千人', meaning: 'せんにん', type: 'number' },
  { word: '千田', meaning: 'ちだ', type: 'surname' },
  { word: '千日', meaning: 'せんにち', type: 'number' },
  { word: '千年', meaning: 'せんねん', type: 'number' },
  { word: '千本', meaning: 'せんぼん', type: 'number' },

  // ========== 川 ==========
  { word: '川上', meaning: 'かわかみ', type: 'general' },
  { word: '川下', meaning: 'かわしも', type: 'general' },
  { word: '川口', meaning: 'かわぐち', type: 'surname' },
  { word: '川中', meaning: 'かわなか', type: 'general' },
  { word: '川田', meaning: 'かわた', type: 'surname' },

  // ========== 先 ==========
  { word: '先月', meaning: 'せんげつ', type: 'general' },
  { word: '先人', meaning: 'せんじん', type: 'general' },
  { word: '先生', meaning: 'せんせい', type: 'general' },
  { word: '先手', meaning: 'せんて', type: 'general' },
  { word: '先入', meaning: 'せんにゅう', type: 'general' },
  { word: '先日', meaning: 'せんじつ', type: 'general' },

  // ========== 早 ==========
  { word: '早口', meaning: 'はやくち', type: 'general' },
  { word: '早川', meaning: 'はやかわ', type: 'surname' },
  { word: '早足', meaning: 'はやあし', type: 'general' },

  // ========== 草 ==========
  { word: '草花', meaning: 'くさばな', type: 'general' },
  { word: '草川', meaning: 'くさかわ', type: 'surname' },
  { word: '草田', meaning: 'くさだ', type: 'surname' },
  { word: '草虫', meaning: 'くさむし', type: 'general' },
  { word: '草木', meaning: 'くさき', type: 'general' },

  // ========== 足 ==========
  { word: '足音', meaning: 'あしおと', type: 'general' },
  { word: '足下', meaning: 'あしもと', type: 'general' },

  // ========== 村 ==========
  { word: '村上', meaning: 'むらかみ', type: 'surname' },
  { word: '村山', meaning: 'むらやま', type: 'surname' },
  { word: '村人', meaning: 'むらびと', type: 'general' },
  { word: '村田', meaning: 'むらた', type: 'surname' },
  { word: '村中', meaning: 'むらなか', type: 'surname' },

  // ========== 大 ==========
  { word: '大雨', meaning: 'おおあめ', type: 'general' },
  { word: '大火', meaning: 'たいか', type: 'general' },
  { word: '大学', meaning: 'だいがく', type: 'general' },
  { word: '大金', meaning: 'たいきん', type: 'general' },
  { word: '大空', meaning: 'おおぞら', type: 'general' },
  { word: '大口', meaning: 'おおぐち', type: 'general' },
  { word: '大山', meaning: 'おおやま', type: 'surname' },
  { word: '大小', meaning: 'だいしょう', type: 'general' },
  { word: '大水', meaning: 'おおみず', type: 'general' },
  { word: '大石', meaning: 'おおいし', type: 'general' },
  { word: '大川', meaning: 'おおかわ', type: 'surname' },
  { word: '大田', meaning: 'おおた', type: 'surname' },
  { word: '大中', meaning: 'だいちゅう', type: 'general' },
  { word: '大人', meaning: 'おとな', type: 'general' },
  { word: '大木', meaning: 'たいぼく', type: 'general' },
  { word: '大森', meaning: 'おおもり', type: 'surname' },
  { word: '大林', meaning: 'おおばやし', type: 'surname' },

  // ========== 男 ==========
  { word: '男子', meaning: 'だんし', type: 'general' },
  { word: '男女', meaning: 'だんじょ', type: 'general' },

  // ========== 竹 ==========
  { word: '竹山', meaning: 'たけやま', type: 'surname' },
  { word: '竹村', meaning: 'たけむら', type: 'surname' },
  { word: '竹田', meaning: 'たけだ', type: 'surname' },
  { word: '竹中', meaning: 'たけなか', type: 'surname' },
  { word: '竹本', meaning: 'たけもと', type: 'surname' },
  { word: '竹林', meaning: 'ちくりん', type: 'general' },

  // ========== 中 ==========
  { word: '中火', meaning: 'ちゅうび', type: 'general' },
  { word: '中学', meaning: 'ちゅうがく', type: 'general' },
  { word: '中川', meaning: 'なかがわ', type: 'surname' },
  { word: '中山', meaning: 'なかやま', type: 'surname' },
  { word: '中村', meaning: 'なかむら', type: 'surname' },
  { word: '中田', meaning: 'なかた', type: 'surname' },
  { word: '中日', meaning: 'ちゅうにち', type: 'general' },
  { word: '中年', meaning: 'ちゅうねん', type: 'general' },

  // ========== 虫 ==========
  { word: '虫目', meaning: 'むしめ', type: 'general' },

  // ========== 町 ==========
  { word: '町人', meaning: 'ちょうにん', type: 'general' },
  { word: '町田', meaning: 'まちだ', type: 'surname' },
  { word: '町中', meaning: 'まちなか', type: 'general' },

  // ========== 天 ==========
  { word: '天王', meaning: 'てんのう', type: 'general' },
  { word: '天下', meaning: 'てんか', type: 'general' },
  { word: '天火', meaning: 'てんぴ', type: 'general' },
  { word: '天気', meaning: 'てんき', type: 'general' },
  { word: '天空', meaning: 'てんくう', type: 'general' },
  { word: '天女', meaning: 'てんにょ', type: 'general' },
  { word: '天上', meaning: 'てんじょう', type: 'general' },
  { word: '天川', meaning: 'あまかわ', type: 'surname' },
  { word: '天田', meaning: 'あまだ', type: 'surname' },
  { word: '天日', meaning: 'てんぴ', type: 'general' },
  { word: '天文', meaning: 'てんもん', type: 'general' },

  // ========== 田 ==========
  { word: '田口', meaning: 'たぐち', type: 'surname' },
  { word: '田中', meaning: 'たなか', type: 'surname' },
  { word: '田村', meaning: 'たむら', type: 'surname' },

  // ========== 土 ==========
  { word: '土山', meaning: 'つちやま', type: 'surname' },
  { word: '土手', meaning: 'どて', type: 'general' },
  { word: '土川', meaning: 'つちかわ', type: 'surname' },
  { word: '土田', meaning: 'つちだ', type: 'surname' },
  { word: '土中', meaning: 'どちゅう', type: 'general' },
  { word: '土日', meaning: 'どにち', type: 'general' },
  { word: '土木', meaning: 'どぼく', type: 'general' },

  // ========== 二 ==========
  { word: '二月', meaning: 'にがつ', type: 'number' },
  { word: '二人', meaning: 'ふたり', type: 'number' },
  { word: '二十', meaning: 'にじゅう', type: 'number' },
  { word: '二日', meaning: 'ふつか', type: 'number' },
  { word: '二本', meaning: 'にほん', type: 'number' },

  // ========== 日 ==========
  { word: '日下', meaning: 'くさか', type: 'surname' },
  { word: '日山', meaning: 'ひやま', type: 'surname' },
  { word: '日出', meaning: 'にっしゅつ', type: 'general' },
  { word: '日中', meaning: 'にっちゅう', type: 'general' },
  { word: '日田', meaning: 'ひた', type: 'surname' },
  { word: '日入', meaning: 'にちにゅう', type: 'general' },
  { word: '日本', meaning: 'にほん・にっぽん', type: 'general' },

  // ========== 入 ==========
  { word: '入学', meaning: 'にゅうがく', type: 'general' },
  { word: '入金', meaning: 'にゅうきん', type: 'general' },
  { word: '入口', meaning: 'いりぐち', type: 'general' },
  { word: '入手', meaning: 'にゅうしゅ', type: 'general' },
  { word: '入水', meaning: 'にゅうすい', type: 'general' },
  { word: '入力', meaning: 'にゅうりょく', type: 'general' },

  // ========== 年 ==========
  { word: '年金', meaning: 'ねんきん', type: 'general' },
  { word: '年月', meaning: 'ねんげつ', type: 'general' },
  { word: '年中', meaning: 'ねんじゅう', type: 'general' },

  // ========== 白 ==========
  { word: '白金', meaning: 'はっきん', type: 'general' },
  { word: '白玉', meaning: 'しらたま', type: 'general' },
  { word: '白糸', meaning: 'しらいと', type: 'general' },
  { word: '白石', meaning: 'しらいし', type: 'surname' },
  { word: '白川', meaning: 'しらかわ', type: 'surname' },
  { word: '白田', meaning: 'しらた', type: 'surname' },
  { word: '白人', meaning: 'はくじん', type: 'general' },
  { word: '白木', meaning: 'しらき', type: 'surname' },
  { word: '白目', meaning: 'しろめ', type: 'general' },

  // ========== 八 ==========
  { word: '八月', meaning: 'はちがつ', type: 'number' },
  { word: '八人', meaning: 'はちにん', type: 'number' },
  { word: '八十', meaning: 'はちじゅう', type: 'number' },
  { word: '八日', meaning: 'ようか', type: 'number' },
  { word: '八本', meaning: 'はっぽん', type: 'number' },
  { word: '八木', meaning: 'やぎ', type: 'surname' },

  // ========== 百 ==========
  { word: '百円', meaning: 'ひゃくえん', type: 'number' },
  { word: '百人', meaning: 'ひゃくにん', type: 'number' },
  { word: '百日', meaning: 'ひゃくにち', type: 'number' },
  { word: '百年', meaning: 'ひゃくねん', type: 'number' },
  { word: '百本', meaning: 'ひゃっぽん', type: 'number' },

  // ========== 文 ==========
  { word: '文中', meaning: 'ぶんちゅう', type: 'general' },
  { word: '文字', meaning: 'もじ', type: 'general' },

  // ========== 木 ==========
  { word: '木下', meaning: 'きのした', type: 'surname' },
  { word: '木山', meaning: 'きやま', type: 'surname' },
  { word: '木石', meaning: 'ぼくせき', type: 'general' },
  { word: '木村', meaning: 'きむら', type: 'surname' },
  { word: '木田', meaning: 'きだ', type: 'surname' },
  { word: '木目', meaning: 'もくめ', type: 'general' },
  { word: '木立', meaning: 'こだち', type: 'general' },

  // ========== 本 ==========
  { word: '本気', meaning: 'ほんき', type: 'general' },
  { word: '本山', meaning: 'ほんざん', type: 'surname' },
  { word: '本人', meaning: 'ほんにん', type: 'general' },
  { word: '本田', meaning: 'ほんだ', type: 'surname' },
  { word: '本日', meaning: 'ほんじつ', type: 'general' },
  { word: '本文', meaning: 'ほんぶん', type: 'general' },
  { word: '本名', meaning: 'ほんみょう', type: 'general' },

  // ========== 名 ==========
  { word: '名月', meaning: 'めいげつ', type: 'general' },
  { word: '名字', meaning: 'みょうじ', type: 'general' },
  { word: '名人', meaning: 'めいじん', type: 'general' },
  { word: '名文', meaning: 'めいぶん', type: 'general' },
  { word: '名目', meaning: 'めいもく', type: 'general' },

  // ========== 目 ==========
  { word: '目下', meaning: 'めした', type: 'general' },
  { word: '目上', meaning: 'めうえ', type: 'general' },
  { word: '目玉', meaning: 'めだま', type: 'general' },
  { word: '目立', meaning: 'めだつ', type: 'general' },

  // ========== 立 ==========
  { word: '立入', meaning: 'たちいり', type: 'general' },

  // ========== 力 ==========
  // 力から始まる熟語は80字内では少ない

  // ========== 林 ==========
  { word: '林山', meaning: 'はやしやま', type: 'surname' },
  { word: '林中', meaning: 'りんちゅう', type: 'general' },
  { word: '林田', meaning: 'はやしだ', type: 'surname' },
  { word: '林本', meaning: 'はやしもと', type: 'surname' },

  // ========== 六 ==========
  { word: '六月', meaning: 'ろくがつ', type: 'number' },
  { word: '六人', meaning: 'ろくにん', type: 'number' },
  { word: '六十', meaning: 'ろくじゅう', type: 'number' },
  { word: '六日', meaning: 'むいか', type: 'number' },
  { word: '六本', meaning: 'ろっぽん', type: 'number' },

  // ========== 追加調査分 ==========

  // 曜日の組み合わせ
  { word: '火水', meaning: 'かすい（火曜水曜）', type: 'general' },
  { word: '水木', meaning: 'すいもく（水曜木曜）', type: 'general' },
  { word: '木金', meaning: 'もくきん（木曜金曜）', type: 'general' },
  { word: '金土', meaning: 'きんど（金曜土曜）', type: 'general' },
  { word: '土日', meaning: 'どにち', type: 'general' },
  { word: '日月', meaning: 'にちげつ', type: 'general' },

  // 数字の連続・組み合わせ
  { word: '一二', meaning: 'いちに', type: 'number' },
  { word: '二三', meaning: 'にさん', type: 'number' },
  { word: '三四', meaning: 'さんし', type: 'number' },
  { word: '四五', meaning: 'しご', type: 'number' },
  { word: '五六', meaning: 'ごろく', type: 'number' },
  { word: '六七', meaning: 'ろくしち', type: 'number' },
  { word: '七八', meaning: 'しちはち', type: 'number' },
  { word: '八九', meaning: 'はっく', type: 'number' },
  { word: '九十', meaning: 'きゅうじゅう', type: 'number' },
  { word: '十一', meaning: 'じゅういち', type: 'number' },
  { word: '十二', meaning: 'じゅうに', type: 'number' },
  { word: '十三', meaning: 'じゅうさん', type: 'number' },
  { word: '十四', meaning: 'じゅうし', type: 'number' },
  { word: '十五', meaning: 'じゅうご', type: 'number' },
  { word: '十六', meaning: 'じゅうろく', type: 'number' },
  { word: '十七', meaning: 'じゅうしち', type: 'number' },
  { word: '十八', meaning: 'じゅうはち', type: 'number' },
  { word: '十九', meaning: 'じゅうく', type: 'number' },
  { word: '二十', meaning: 'にじゅう', type: 'number' },
  { word: '三十', meaning: 'さんじゅう', type: 'number' },
  { word: '四十', meaning: 'しじゅう・よんじゅう', type: 'number' },
  { word: '五十', meaning: 'ごじゅう', type: 'number' },
  { word: '六十', meaning: 'ろくじゅう', type: 'number' },
  { word: '七十', meaning: 'しちじゅう・ななじゅう', type: 'number' },
  { word: '八十', meaning: 'はちじゅう', type: 'number' },
  { word: '九十', meaning: 'きゅうじゅう', type: 'number' },

  // 追加の一般熟語
  { word: '上中', meaning: 'じょうちゅう', type: 'general' },
  { word: '中下', meaning: 'ちゅうか', type: 'general' },
  { word: '上中下', meaning: 'じょうちゅうげ', type: 'general' },
  { word: '大中小', meaning: 'だいちゅうしょう', type: 'general' },
  { word: '目先', meaning: 'めさき', type: 'general' },
  { word: '手元', meaning: 'てもと', type: 'general' },
  { word: '足元', meaning: 'あしもと', type: 'general' },
  { word: '耳元', meaning: 'みみもと', type: 'general' },
  { word: '口元', meaning: 'くちもと', type: 'general' },
  { word: '山手', meaning: 'やまて', type: 'general' },
  { word: '川手', meaning: 'かわて', type: 'general' },
  { word: '田畑', meaning: 'たはた', type: 'general' },
  { word: '山田', meaning: 'やまだ', type: 'surname' },
  { word: '川田', meaning: 'かわた', type: 'surname' },
  { word: '田川', meaning: 'たがわ', type: 'surname' },
  { word: '山川', meaning: 'やまかわ', type: 'surname' },
  { word: '川山', meaning: 'かわやま', type: 'surname' },
  { word: '石田', meaning: 'いしだ', type: 'surname' },
  { word: '田石', meaning: 'たいし', type: 'surname' },
  { word: '金石', meaning: 'きんせき', type: 'general' },
  { word: '玉石', meaning: 'ぎょくせき', type: 'general' },
  { word: '火水', meaning: 'かすい', type: 'general' },
  { word: '水火', meaning: 'すいか', type: 'general' },
  { word: '天地', meaning: 'てんち', type: 'general' },
  { word: '天人', meaning: 'てんにん', type: 'general' },
  { word: '人天', meaning: 'にんてん', type: 'general' },
  { word: '天水', meaning: 'てんすい', type: 'general' },
  { word: '天火', meaning: 'てんぴ', type: 'general' },
  { word: '火天', meaning: 'かてん', type: 'general' },
  { word: '水天', meaning: 'すいてん', type: 'general' },
  { word: '金木', meaning: 'かなき', type: 'general' },
  { word: '木金', meaning: 'もっきん', type: 'general' },
  { word: '火木', meaning: 'かもく（火曜木曜）', type: 'general' },
  { word: '月水', meaning: 'げっすい（月曜水曜）', type: 'general' },
  { word: '月木', meaning: 'げつもく（月曜木曜）', type: 'general' },
  { word: '火金', meaning: 'かきん（火曜金曜）', type: 'general' },
  { word: '水金', meaning: 'すいきん', type: 'general' },
  { word: '木土', meaning: 'もくど（木曜土曜）', type: 'general' },

  // 追加の苗字
  { word: '松田', meaning: 'まつだ', type: 'surname' },
  { word: '井上', meaning: 'いのうえ', type: 'surname' },
  { word: '井田', meaning: 'いだ', type: 'surname' },
  { word: '井川', meaning: 'いかわ', type: 'surname' },
  { word: '井口', meaning: 'いぐち', type: 'surname' },
  { word: '井中', meaning: 'いなか', type: 'surname' },
  { word: '田井', meaning: 'たい', type: 'surname' },
  { word: '山井', meaning: 'やまい', type: 'surname' },
  { word: '川井', meaning: 'かわい', type: 'surname' },
  { word: '石井', meaning: 'いしい', type: 'surname' },
  { word: '金井', meaning: 'かない', type: 'surname' },
  { word: '今井', meaning: 'いまい', type: 'surname' },
  { word: '古田', meaning: 'ふるた', type: 'surname' },
  { word: '古川', meaning: 'ふるかわ', type: 'surname' },
  { word: '古山', meaning: 'ふるやま', type: 'surname' },
  { word: '新田', meaning: 'にった', type: 'surname' },
  { word: '前田', meaning: 'まえだ', type: 'surname' },
  { word: '内田', meaning: 'うちだ', type: 'surname' },
  { word: '内山', meaning: 'うちやま', type: 'surname' },
  { word: '内川', meaning: 'うちかわ', type: 'surname' },
  { word: '外山', meaning: 'とやま', type: 'surname' },
  { word: '外川', meaning: 'そとかわ', type: 'surname' },
  { word: '長田', meaning: 'ながた', type: 'surname' },
  { word: '長山', meaning: 'ながやま', type: 'surname' },
  { word: '長川', meaning: 'ながかわ', type: 'surname' },
  { word: '野田', meaning: 'のだ', type: 'surname' },
  { word: '野山', meaning: 'のやま', type: 'surname' },
  { word: '野川', meaning: 'のがわ', type: 'surname' },
  { word: '野村', meaning: 'のむら', type: 'surname' },
  { word: '野中', meaning: 'のなか', type: 'surname' },
  { word: '野口', meaning: 'のぐち', type: 'surname' },
  { word: '野木', meaning: 'のぎ', type: 'surname' },
  { word: '野本', meaning: 'のもと', type: 'surname' },
  { word: '原田', meaning: 'はらだ', type: 'surname' },
  { word: '原山', meaning: 'はらやま', type: 'surname' },
  { word: '原川', meaning: 'はらかわ', type: 'surname' },
  { word: '原口', meaning: 'はらぐち', type: 'surname' },
  { word: '岡田', meaning: 'おかだ', type: 'surname' },
  { word: '岡山', meaning: 'おかやま', type: 'surname' },
  { word: '岡本', meaning: 'おかもと', type: 'surname' },
  { word: '岡村', meaning: 'おかむら', type: 'surname' },
  { word: '岡川', meaning: 'おかがわ', type: 'surname' },
  { word: '西田', meaning: 'にしだ', type: 'surname' },
  { word: '西山', meaning: 'にしやま', type: 'surname' },
  { word: '西川', meaning: 'にしかわ', type: 'surname' },
  { word: '西村', meaning: 'にしむら', type: 'surname' },
  { word: '西本', meaning: 'にしもと', type: 'surname' },
  { word: '東田', meaning: 'ひがしだ', type: 'surname' },
  { word: '東山', meaning: 'ひがしやま', type: 'surname' },
  { word: '東川', meaning: 'ひがしかわ', type: 'surname' },
  { word: '南田', meaning: 'みなみだ', type: 'surname' },
  { word: '南山', meaning: 'みなみやま', type: 'surname' },
  { word: '南川', meaning: 'みなみかわ', type: 'surname' },
  { word: '北田', meaning: 'きただ', type: 'surname' },
  { word: '北山', meaning: 'きたやま', type: 'surname' },
  { word: '北川', meaning: 'きたがわ', type: 'surname' },
  { word: '北村', meaning: 'きたむら', type: 'surname' },

  // 追加の一般熟語（80字内で作れるもの）
  { word: '王立', meaning: 'おうりつ', type: 'general' },
  { word: '立王', meaning: 'りつおう', type: 'general' },
  { word: '立山', meaning: 'たてやま', type: 'general' },
  { word: '立川', meaning: 'たちかわ', type: 'surname' },
  { word: '立田', meaning: 'たつた', type: 'surname' },
  { word: '立石', meaning: 'たていし', type: 'surname' },
  { word: '立木', meaning: 'たちき', type: 'general' },
  { word: '立花', meaning: 'たちばな', type: 'surname' },
  { word: '早生', meaning: 'わせ', type: 'general' },
  { word: '早天', meaning: 'そうてん', type: 'general' },
  { word: '早朝', meaning: 'そうちょう', type: 'general' },
  { word: '早目', meaning: 'はやめ', type: 'general' },
  { word: '早手', meaning: 'はやて', type: 'general' },
  { word: '草山', meaning: 'くさやま', type: 'surname' },
  { word: '草原', meaning: 'くさはら', type: 'general' },
  { word: '青天', meaning: 'せいてん', type: 'general' },
  { word: '青火', meaning: 'あおび', type: 'general' },
  { word: '青白', meaning: 'あおじろ', type: 'general' },
  { word: '白青', meaning: 'しろあお', type: 'general' },
  { word: '赤白', meaning: 'あかしろ', type: 'general' },
  { word: '白赤', meaning: 'しろあか', type: 'general' },
  { word: '赤青', meaning: 'あかあお', type: 'general' },
  { word: '金銀', meaning: 'きんぎん', type: 'general' },
  { word: '金白', meaning: 'きんぱく', type: 'general' },
  { word: '白金', meaning: 'はっきん', type: 'general' },
  { word: '赤金', meaning: 'あかがね', type: 'general' },
  { word: '青金', meaning: 'あおがね', type: 'general' },
  { word: '玉金', meaning: 'ぎょっきん', type: 'general' },
  { word: '石金', meaning: 'いしがね', type: 'general' },
  { word: '土金', meaning: 'どきん（土曜金曜）', type: 'general' },
  { word: '火土', meaning: 'かど（火曜土曜）', type: 'general' },
  { word: '日火', meaning: 'にちか（日曜火曜）', type: 'general' },
  { word: '日水', meaning: 'にっすい', type: 'general' },
  { word: '日木', meaning: 'にちもく', type: 'general' },
  { word: '日金', meaning: 'にちきん', type: 'general' },
  { word: '日土', meaning: 'にちど', type: 'general' },
  { word: '月土', meaning: 'げつど', type: 'general' },
  { word: '月日', meaning: 'つきひ・がっぴ', type: 'general' },
  { word: '年月日', meaning: 'ねんがっぴ', type: 'general' },
  { word: '生年月日', meaning: 'せいねんがっぴ', type: 'general' },
  { word: '生月', meaning: 'せいげつ', type: 'general' },
  { word: '生日', meaning: 'せいじつ', type: 'general' },
  { word: '生人', meaning: 'せいじん・なまびと', type: 'general' },
  { word: '人見', meaning: 'ひとみ', type: 'surname' },
  { word: '見人', meaning: 'けんにん', type: 'general' },
  { word: '犬山', meaning: 'いぬやま', type: 'surname' },
  { word: '犬田', meaning: 'いぬた', type: 'surname' },
  { word: '犬川', meaning: 'いぬかわ', type: 'surname' },
  { word: '大犬', meaning: 'おおいぬ', type: 'general' },
  { word: '小犬', meaning: 'こいぬ', type: 'general' },
  { word: '子犬', meaning: 'こいぬ', type: 'general' },
  { word: '雨雲', meaning: 'あまぐも', type: 'general' },
  { word: '雨足', meaning: 'あまあし', type: 'general' },
  { word: '雨上', meaning: 'あまあがり', type: 'general' },
  { word: '雨下', meaning: 'うか', type: 'general' },
  { word: '大雪', meaning: 'おおゆき', type: 'general' },
  { word: '小雪', meaning: 'こゆき', type: 'general' },
  { word: '花雨', meaning: 'かう', type: 'general' },
  { word: '雨花', meaning: 'うか', type: 'general' },
  { word: '花月', meaning: 'かげつ', type: 'general' },
  { word: '月花', meaning: 'げっか', type: 'general' },
  { word: '花天', meaning: 'かてん', type: 'general' },
  { word: '天花', meaning: 'てんか', type: 'general' },
  { word: '花草', meaning: 'かそう', type: 'general' },
  { word: '草花', meaning: 'くさばな', type: 'general' },
  { word: '花川', meaning: 'はなかわ', type: 'surname' },
  { word: '花村', meaning: 'はなむら', type: 'surname' },
  { word: '花本', meaning: 'はなもと', type: 'surname' },
  { word: '花中', meaning: 'はななか', type: 'surname' },
  { word: '音田', meaning: 'おとだ', type: 'surname' },
  { word: '音川', meaning: 'おとかわ', type: 'surname' },
  { word: '音山', meaning: 'おとやま', type: 'surname' },
  { word: '大音', meaning: 'おおおと', type: 'general' },
  { word: '小音', meaning: 'しょうおん', type: 'general' },
  { word: '火山', meaning: 'かざん', type: 'general' },
  { word: '山火', meaning: 'やまび', type: 'general' },
  { word: '火中', meaning: 'かちゅう', type: 'general' },
  { word: '中火', meaning: 'ちゅうび', type: 'general' },
  { word: '火水', meaning: 'かすい', type: 'general' },
  { word: '水火', meaning: 'すいか', type: 'general' },
  { word: '火金', meaning: 'ひがね', type: 'general' },
  { word: '金火', meaning: 'きんか', type: 'general' },
  { word: '火花', meaning: 'ひばな', type: 'general' },
  { word: '花火', meaning: 'はなび', type: 'general' },
  { word: '火玉', meaning: 'ひだま', type: 'general' },
  { word: '玉火', meaning: 'たまび', type: 'general' },
  { word: '火日', meaning: 'かじつ', type: 'general' },
  { word: '日火', meaning: 'にちか', type: 'general' },
  { word: '火天', meaning: 'かてん', type: 'general' },
  { word: '天火', meaning: 'てんび', type: 'general' },
  { word: '土火', meaning: 'どか', type: 'general' },
  { word: '火土', meaning: 'かど', type: 'general' },
  { word: '貝田', meaning: 'かいだ', type: 'surname' },
  { word: '貝山', meaning: 'かいやま', type: 'surname' },
  { word: '貝川', meaning: 'かいかわ', type: 'surname' },
  { word: '金貝', meaning: 'かながい', type: 'general' },
  { word: '学田', meaning: 'がくでん', type: 'general' },
  { word: '学山', meaning: 'がくざん', type: 'general' },
  { word: '学人', meaning: 'がくじん', type: 'general' },
  { word: '人学', meaning: 'じんがく', type: 'general' },
  { word: '気山', meaning: 'きやま', type: 'surname' },
  { word: '気田', meaning: 'きだ', type: 'surname' },
  { word: '大気', meaning: 'たいき', type: 'general' },
  { word: '小気', meaning: 'しょうき', type: 'general' },
  { word: '人気', meaning: 'にんき', type: 'general' },
  { word: '気人', meaning: 'きじん', type: 'general' },
  { word: '本気', meaning: 'ほんき', type: 'general' },
  { word: '気本', meaning: 'きほん', type: 'general' },
  { word: '元気', meaning: 'げんき', type: 'general' },
  { word: '気元', meaning: 'きげん', type: 'general' },
  { word: '空気', meaning: 'くうき', type: 'general' },
  { word: '気空', meaning: 'きくう', type: 'general' },
  { word: '天気', meaning: 'てんき', type: 'general' },
  { word: '気天', meaning: 'きてん', type: 'general' },
  { word: '休山', meaning: 'きゅうざん', type: 'general' },
  { word: '休田', meaning: 'きゅうでん', type: 'general' },
  { word: '休日', meaning: 'きゅうじつ', type: 'general' },
  { word: '日休', meaning: 'にちきゅう', type: 'general' },
  { word: '休火', meaning: 'きゅうか', type: 'general' },
  { word: '火休', meaning: 'かきゅう', type: 'general' },
  { word: '休学', meaning: 'きゅうがく', type: 'general' },
  { word: '学休', meaning: 'がっきゅう', type: 'general' },
  { word: '玉山', meaning: 'たまやま', type: 'surname' },
  { word: '山玉', meaning: 'やまたま', type: 'general' },
  { word: '玉川', meaning: 'たまがわ', type: 'surname' },
  { word: '川玉', meaning: 'かわたま', type: 'general' },
  { word: '玉村', meaning: 'たまむら', type: 'surname' },
  { word: '村玉', meaning: 'むらたま', type: 'general' },
  { word: '玉田', meaning: 'たまだ', type: 'surname' },
  { word: '田玉', meaning: 'たたま', type: 'general' },
  { word: '金川', meaning: 'かながわ', type: 'surname' },
  { word: '川金', meaning: 'かわかね', type: 'general' },
  { word: '金村', meaning: 'かなむら', type: 'surname' },
  { word: '村金', meaning: 'むらかね', type: 'general' },
  { word: '金中', meaning: 'かなか', type: 'surname' },
  { word: '中金', meaning: 'なかがね', type: 'surname' },
  { word: '金林', meaning: 'かなばやし', type: 'surname' },
  { word: '林金', meaning: 'はやしかね', type: 'surname' },
  { word: '空山', meaning: 'くうざん', type: 'general' },
  { word: '山空', meaning: 'やまぞら', type: 'general' },
  { word: '空田', meaning: 'そらた', type: 'surname' },
  { word: '田空', meaning: 'たぞら', type: 'general' },
  { word: '空村', meaning: 'そらむら', type: 'surname' },
  { word: '村空', meaning: 'むらぞら', type: 'general' },
  { word: '空川', meaning: 'そらかわ', type: 'surname' },
  { word: '川空', meaning: 'かわぞら', type: 'general' },
  { word: '空木', meaning: 'うつぎ', type: 'general' },
  { word: '木空', meaning: 'きくう', type: 'general' },
  { word: '空人', meaning: 'くうじん', type: 'general' },
  { word: '人空', meaning: 'じんくう', type: 'general' },
  { word: '空地', meaning: 'あきち', type: 'general' },
  { word: '地空', meaning: 'ちくう', type: 'general' },
  { word: '月山', meaning: 'がっさん', type: 'general' },
  { word: '山月', meaning: 'さんげつ', type: 'general' },
  { word: '月川', meaning: 'つきかわ', type: 'surname' },
  { word: '川月', meaning: 'かわつき', type: 'surname' },
  { word: '月村', meaning: 'つきむら', type: 'surname' },
  { word: '村月', meaning: 'むらつき', type: 'surname' },
  { word: '月本', meaning: 'つきもと', type: 'surname' },
  { word: '本月', meaning: 'ほんげつ', type: 'general' },
  { word: '見山', meaning: 'みやま', type: 'surname' },
  { word: '山見', meaning: 'やまみ', type: 'surname' },
  { word: '見田', meaning: 'みた', type: 'surname' },
  { word: '田見', meaning: 'たみ', type: 'surname' },
  { word: '見川', meaning: 'みかわ', type: 'surname' },
  { word: '川見', meaning: 'かわみ', type: 'surname' },
  { word: '五山', meaning: 'ござん', type: 'general' },
  { word: '山五', meaning: 'やまご', type: 'general' },
  { word: '五田', meaning: 'ごた', type: 'surname' },
  { word: '田五', meaning: 'たご', type: 'general' },
  { word: '口山', meaning: 'くちやま', type: 'surname' },
  { word: '山口', meaning: 'やまぐち', type: 'surname' },
  { word: '口田', meaning: 'くちだ', type: 'surname' },
  { word: '田口', meaning: 'たぐち', type: 'surname' },
  { word: '口川', meaning: 'くちかわ', type: 'surname' },
  { word: '川口', meaning: 'かわぐち', type: 'surname' },
  { word: '口中', meaning: 'こうちゅう', type: 'general' },
  { word: '中口', meaning: 'なかぐち', type: 'surname' },
  { word: '校山', meaning: 'こうざん', type: 'general' },
  { word: '山校', meaning: 'さんこう', type: 'general' },
  { word: '校田', meaning: 'こうでん', type: 'general' },
  { word: '田校', meaning: 'でんこう', type: 'general' },
  { word: '校中', meaning: 'こうちゅう', type: 'general' },
  { word: '中校', meaning: 'ちゅうこう', type: 'general' },
  { word: '山左', meaning: 'やまひだり', type: 'general' },
  { word: '左山', meaning: 'ひだりやま', type: 'general' },
  { word: '右山', meaning: 'みぎやま', type: 'general' },
  { word: '山右', meaning: 'やまみぎ', type: 'general' },
  { word: '子山', meaning: 'こやま', type: 'surname' },
  { word: '山子', meaning: 'やまこ', type: 'general' },
  { word: '子田', meaning: 'こだ', type: 'surname' },
  { word: '田子', meaning: 'たご', type: 'surname' },
  { word: '子川', meaning: 'こかわ', type: 'surname' },
  { word: '川子', meaning: 'かわこ', type: 'surname' },
  { word: '糸山', meaning: 'いとやま', type: 'surname' },
  { word: '山糸', meaning: 'やまいと', type: 'general' },
  { word: '糸田', meaning: 'いとだ', type: 'surname' },
  { word: '田糸', meaning: 'たいと', type: 'general' },
  { word: '糸川', meaning: 'いとかわ', type: 'surname' },
  { word: '川糸', meaning: 'かわいと', type: 'general' },
  { word: '糸村', meaning: 'いとむら', type: 'surname' },
  { word: '村糸', meaning: 'むらいと', type: 'general' },
  { word: '字山', meaning: 'じやま', type: 'surname' },
  { word: '山字', meaning: 'やまじ', type: 'general' },
  { word: '字田', meaning: 'じた', type: 'surname' },
  { word: '田字', meaning: 'たじ', type: 'general' },
  { word: '耳山', meaning: 'みみやま', type: 'surname' },
  { word: '山耳', meaning: 'やまみみ', type: 'general' },
  { word: '耳田', meaning: 'みみた', type: 'surname' },
  { word: '田耳', meaning: 'たみみ', type: 'general' },
  { word: '車山', meaning: 'くるまやま', type: 'surname' },
  { word: '山車', meaning: 'だし', type: 'general' },
  { word: '車田', meaning: 'くるまだ', type: 'surname' },
  { word: '田車', meaning: 'たぐるま', type: 'general' },
  { word: '車川', meaning: 'くるまかわ', type: 'surname' },
  { word: '川車', meaning: 'かわぐるま', type: 'general' },
  { word: '大車', meaning: 'おおぐるま', type: 'general' },
  { word: '車大', meaning: 'くるまおお', type: 'general' },
  { word: '小車', meaning: 'こぐるま', type: 'general' },
  { word: '車小', meaning: 'くるまこ', type: 'general' },
  { word: '手山', meaning: 'てやま', type: 'surname' },
  { word: '山手', meaning: 'やまて', type: 'general' },
  { word: '手田', meaning: 'てだ', type: 'surname' },
  { word: '田手', meaning: 'たて', type: 'general' },
  { word: '手川', meaning: 'てかわ', type: 'surname' },
  { word: '川手', meaning: 'かわて', type: 'general' },
  { word: '手村', meaning: 'てむら', type: 'surname' },
  { word: '村手', meaning: 'むらて', type: 'general' },
  { word: '出山', meaning: 'でやま', type: 'surname' },
  { word: '山出', meaning: 'やまで', type: 'general' },
  { word: '出田', meaning: 'でた', type: 'surname' },
  { word: '田出', meaning: 'たで', type: 'general' },
  { word: '出川', meaning: 'でがわ', type: 'surname' },
  { word: '川出', meaning: 'かわで', type: 'general' },
  { word: '女山', meaning: 'おんなやま', type: 'surname' },
  { word: '山女', meaning: 'やまめ', type: 'general' },
  { word: '女田', meaning: 'おんなだ', type: 'surname' },
  { word: '田女', meaning: 'たおんな', type: 'general' },
  { word: '女川', meaning: 'おながわ', type: 'surname' },
  { word: '川女', meaning: 'かわめ', type: 'general' },
  { word: '人山', meaning: 'ひとやま', type: 'general' },
  { word: '山人', meaning: 'さんじん', type: 'general' },
  { word: '人田', meaning: 'ひとだ', type: 'surname' },
  { word: '田人', meaning: 'たびと', type: 'general' },
  { word: '人川', meaning: 'ひとかわ', type: 'surname' },
  { word: '川人', meaning: 'かわと', type: 'surname' },
  { word: '水山', meaning: 'みずやま', type: 'surname' },
  { word: '山水', meaning: 'さんすい', type: 'general' },
  { word: '水川', meaning: 'みずかわ', type: 'surname' },
  { word: '川水', meaning: 'かわみず', type: 'general' },
  { word: '水村', meaning: 'みずむら', type: 'surname' },
  { word: '村水', meaning: 'むらみず', type: 'general' },
  { word: '正山', meaning: 'まさやま', type: 'surname' },
  { word: '山正', meaning: 'やままさ', type: 'surname' },
  { word: '正田', meaning: 'しょうだ', type: 'surname' },
  { word: '田正', meaning: 'たまさ', type: 'surname' },
  { word: '正川', meaning: 'まさかわ', type: 'surname' },
  { word: '川正', meaning: 'かわまさ', type: 'surname' },
  { word: '正村', meaning: 'まさむら', type: 'surname' },
  { word: '村正', meaning: 'むらまさ', type: 'surname' },
  { word: '生山', meaning: 'いくやま', type: 'surname' },
  { word: '山生', meaning: 'やまおい', type: 'general' },
  { word: '生川', meaning: 'いくかわ', type: 'surname' },
  { word: '川生', meaning: 'かわお', type: 'general' },
  { word: '生村', meaning: 'いくむら', type: 'surname' },
  { word: '村生', meaning: 'むらお', type: 'general' },
  { word: '夕山', meaning: 'ゆうやま', type: 'surname' },
  { word: '山夕', meaning: 'やまゆう', type: 'general' },
  { word: '夕田', meaning: 'ゆうだ', type: 'surname' },
  { word: '田夕', meaning: 'たゆう', type: 'general' },
  { word: '夕川', meaning: 'ゆうかわ', type: 'surname' },
  { word: '川夕', meaning: 'かわゆう', type: 'general' },
  { word: '石村', meaning: 'いしむら', type: 'surname' },
  { word: '村石', meaning: 'むらいし', type: 'surname' },
  { word: '石中', meaning: 'いしなか', type: 'surname' },
  { word: '中石', meaning: 'なかいし', type: 'surname' },
  { word: '石本', meaning: 'いしもと', type: 'surname' },
  { word: '本石', meaning: 'もといし', type: 'surname' },
  { word: '石林', meaning: 'いしばやし', type: 'surname' },
  { word: '林石', meaning: 'はやしいし', type: 'surname' },
  { word: '赤山', meaning: 'あかやま', type: 'surname' },
  { word: '山赤', meaning: 'やまあか', type: 'general' },
  { word: '赤村', meaning: 'あかむら', type: 'surname' },
  { word: '村赤', meaning: 'むらあか', type: 'general' },
  { word: '赤石', meaning: 'あかいし', type: 'surname' },
  { word: '石赤', meaning: 'いしあか', type: 'general' },
  { word: '千川', meaning: 'せんかわ', type: 'surname' },
  { word: '川千', meaning: 'かわせん', type: 'general' },
  { word: '千山', meaning: 'せんざん', type: 'general' },
  { word: '山千', meaning: 'やません', type: 'general' },
  { word: '千村', meaning: 'ちむら', type: 'surname' },
  { word: '村千', meaning: 'むらせん', type: 'general' },
  { word: '千石', meaning: 'せんごく', type: 'surname' },
  { word: '石千', meaning: 'いしせん', type: 'general' },
  { word: '川村', meaning: 'かわむら', type: 'surname' },
  { word: '村川', meaning: 'むらかわ', type: 'surname' },
  { word: '川中', meaning: 'かわなか', type: 'surname' },
  { word: '中川', meaning: 'なかがわ', type: 'surname' },
  { word: '川本', meaning: 'かわもと', type: 'surname' },
  { word: '本川', meaning: 'もとかわ', type: 'surname' },
  { word: '川林', meaning: 'かわばやし', type: 'surname' },
  { word: '林川', meaning: 'はやしかわ', type: 'surname' },
  { word: '先山', meaning: 'さきやま', type: 'surname' },
  { word: '山先', meaning: 'やまさき', type: 'surname' },
  { word: '先田', meaning: 'さきだ', type: 'surname' },
  { word: '田先', meaning: 'たさき', type: 'surname' },
  { word: '先川', meaning: 'さきかわ', type: 'surname' },
  { word: '川先', meaning: 'かわさき', type: 'surname' },
  { word: '早山', meaning: 'はややま', type: 'surname' },
  { word: '山早', meaning: 'やまはや', type: 'surname' },
  { word: '早田', meaning: 'はやた', type: 'surname' },
  { word: '田早', meaning: 'たはや', type: 'surname' },
  { word: '足山', meaning: 'あしやま', type: 'surname' },
  { word: '山足', meaning: 'やまあし', type: 'general' },
  { word: '足田', meaning: 'あしだ', type: 'surname' },
  { word: '田足', meaning: 'たあし', type: 'general' },
  { word: '足川', meaning: 'あしかわ', type: 'surname' },
  { word: '川足', meaning: 'かわあし', type: 'general' },
  { word: '大村', meaning: 'おおむら', type: 'surname' },
  { word: '村大', meaning: 'むらおお', type: 'general' },
  { word: '大本', meaning: 'おおもと', type: 'surname' },
  { word: '本大', meaning: 'もとおお', type: 'general' },
  { word: '大手', meaning: 'おおて', type: 'general' },
  { word: '手大', meaning: 'ておお', type: 'general' },
  { word: '大足', meaning: 'おおあし', type: 'general' },
  { word: '足大', meaning: 'あしおお', type: 'general' },
  { word: '大月', meaning: 'おおつき', type: 'surname' },
  { word: '月大', meaning: 'つきおお', type: 'general' },
  { word: '大日', meaning: 'だいにち', type: 'general' },
  { word: '日大', meaning: 'にちだい', type: 'general' },
  { word: '大年', meaning: 'おおとし', type: 'general' },
  { word: '年大', meaning: 'としおお', type: 'general' },
  { word: '男山', meaning: 'おとこやま', type: 'general' },
  { word: '山男', meaning: 'やまおとこ', type: 'general' },
  { word: '男田', meaning: 'おだ', type: 'surname' },
  { word: '田男', meaning: 'たお', type: 'general' },
  { word: '男川', meaning: 'おがわ', type: 'surname' },
  { word: '川男', meaning: 'かわお', type: 'general' },
  { word: '竹川', meaning: 'たけかわ', type: 'surname' },
  { word: '川竹', meaning: 'かわたけ', type: 'surname' },
  { word: '竹石', meaning: 'たけいし', type: 'surname' },
  { word: '石竹', meaning: 'せきちく', type: 'general' },
  { word: '中本', meaning: 'なかもと', type: 'surname' },
  { word: '本中', meaning: 'ほんなか', type: 'general' },
  { word: '中林', meaning: 'なかばやし', type: 'surname' },
  { word: '林中', meaning: 'はやしなか', type: 'surname' },
  { word: '中森', meaning: 'なかもり', type: 'surname' },
  { word: '森中', meaning: 'もりなか', type: 'surname' },
  { word: '中石', meaning: 'なかいし', type: 'surname' },
  { word: '石中', meaning: 'いしなか', type: 'surname' },
  { word: '虫田', meaning: 'むしだ', type: 'surname' },
  { word: '田虫', meaning: 'たむし', type: 'general' },
  { word: '虫川', meaning: 'むしかわ', type: 'surname' },
  { word: '川虫', meaning: 'かわむし', type: 'general' },
  { word: '虫山', meaning: 'むしやま', type: 'surname' },
  { word: '山虫', meaning: 'やまむし', type: 'general' },
  { word: '町山', meaning: 'まちやま', type: 'surname' },
  { word: '山町', meaning: 'やままち', type: 'general' },
  { word: '町川', meaning: 'まちかわ', type: 'surname' },
  { word: '川町', meaning: 'かわまち', type: 'general' },
  { word: '町村', meaning: 'ちょうそん', type: 'general' },
  { word: '村町', meaning: 'むらまち', type: 'general' },
  { word: '天山', meaning: 'てんざん', type: 'general' },
  { word: '山天', meaning: 'やまてん', type: 'general' },
  { word: '天中', meaning: 'てんちゅう', type: 'general' },
  { word: '中天', meaning: 'ちゅうてん', type: 'general' },
  { word: '天地', meaning: 'てんち', type: 'general' },
  { word: '地天', meaning: 'ちてん', type: 'general' },
  { word: '田山', meaning: 'たやま', type: 'surname' },
  { word: '山田', meaning: 'やまだ', type: 'surname' },
  { word: '田川', meaning: 'たがわ', type: 'surname' },
  { word: '川田', meaning: 'かわた', type: 'surname' },
  { word: '田本', meaning: 'たもと', type: 'surname' },
  { word: '本田', meaning: 'ほんだ', type: 'surname' },
  { word: '田林', meaning: 'たばやし', type: 'surname' },
  { word: '林田', meaning: 'はやしだ', type: 'surname' },
  { word: '土石', meaning: 'どせき', type: 'general' },
  { word: '石土', meaning: 'いしつち', type: 'general' },
  { word: '土人', meaning: 'どじん', type: 'general' },
  { word: '人土', meaning: 'じんど', type: 'general' },
  { word: '土水', meaning: 'どすい', type: 'general' },
  { word: '水土', meaning: 'すいど', type: 'general' },
  { word: '土気', meaning: 'どき', type: 'general' },
  { word: '気土', meaning: 'きど', type: 'general' },
  { word: '二山', meaning: 'にやま', type: 'surname' },
  { word: '山二', meaning: 'やまに', type: 'general' },
  { word: '二川', meaning: 'にかわ', type: 'surname' },
  { word: '川二', meaning: 'かわに', type: 'general' },
  { word: '二村', meaning: 'にむら', type: 'surname' },
  { word: '村二', meaning: 'むらに', type: 'general' },
  { word: '日川', meaning: 'ひかわ', type: 'surname' },
  { word: '川日', meaning: 'かわひ', type: 'general' },
  { word: '日村', meaning: 'ひむら', type: 'surname' },
  { word: '村日', meaning: 'むらひ', type: 'general' },
  { word: '日林', meaning: 'ひばやし', type: 'surname' },
  { word: '林日', meaning: 'はやしひ', type: 'surname' },
  { word: '入山', meaning: 'いりやま', type: 'surname' },
  { word: '山入', meaning: 'やまいり', type: 'general' },
  { word: '入田', meaning: 'いりた', type: 'surname' },
  { word: '田入', meaning: 'たいり', type: 'general' },
  { word: '入川', meaning: 'いりかわ', type: 'surname' },
  { word: '川入', meaning: 'かわいり', type: 'general' },
  { word: '年山', meaning: 'としやま', type: 'surname' },
  { word: '山年', meaning: 'やまとし', type: 'general' },
  { word: '年田', meaning: 'としだ', type: 'surname' },
  { word: '田年', meaning: 'たとし', type: 'general' },
  { word: '年川', meaning: 'としかわ', type: 'surname' },
  { word: '川年', meaning: 'かわとし', type: 'general' },
  { word: '白山', meaning: 'はくさん', type: 'general' },
  { word: '山白', meaning: 'やましろ', type: 'general' },
  { word: '白村', meaning: 'しらむら', type: 'surname' },
  { word: '村白', meaning: 'むらしろ', type: 'surname' },
  { word: '白中', meaning: 'しらなか', type: 'surname' },
  { word: '中白', meaning: 'なかしろ', type: 'surname' },
  { word: '八山', meaning: 'やつやま', type: 'surname' },
  { word: '山八', meaning: 'やまはち', type: 'general' },
  { word: '八田', meaning: 'はった', type: 'surname' },
  { word: '田八', meaning: 'たはち', type: 'general' },
  { word: '八川', meaning: 'やつかわ', type: 'surname' },
  { word: '川八', meaning: 'かわはち', type: 'general' },
  { word: '百山', meaning: 'ももやま', type: 'surname' },
  { word: '山百', meaning: 'やまもも', type: 'general' },
  { word: '百田', meaning: 'ももた', type: 'surname' },
  { word: '田百', meaning: 'たもも', type: 'general' },
  { word: '百川', meaning: 'ももかわ', type: 'surname' },
  { word: '川百', meaning: 'かわもも', type: 'general' },
  { word: '文山', meaning: 'ぶんざん', type: 'general' },
  { word: '山文', meaning: 'やまぶん', type: 'general' },
  { word: '文田', meaning: 'ふみた', type: 'surname' },
  { word: '田文', meaning: 'たぶん', type: 'general' },
  { word: '文川', meaning: 'ふみかわ', type: 'surname' },
  { word: '川文', meaning: 'かわぶん', type: 'general' },
  { word: '木川', meaning: 'きかわ', type: 'surname' },
  { word: '川木', meaning: 'かわき', type: 'surname' },
  { word: '木中', meaning: 'きなか', type: 'surname' },
  { word: '中木', meaning: 'なかき', type: 'surname' },
  { word: '木本', meaning: 'きもと', type: 'surname' },
  { word: '本木', meaning: 'もとき', type: 'surname' },
  { word: '本村', meaning: 'もとむら', type: 'surname' },
  { word: '村本', meaning: 'むらもと', type: 'surname' },
  { word: '本林', meaning: 'もとばやし', type: 'surname' },
  { word: '林本', meaning: 'はやしもと', type: 'surname' },
  { word: '本中', meaning: 'もとなか', type: 'surname' },
  { word: '中本', meaning: 'なかもと', type: 'surname' },
  { word: '名山', meaning: 'めいざん', type: 'general' },
  { word: '山名', meaning: 'やまな', type: 'surname' },
  { word: '名田', meaning: 'なだ', type: 'surname' },
  { word: '田名', meaning: 'たな', type: 'surname' },
  { word: '名川', meaning: 'なかわ', type: 'surname' },
  { word: '川名', meaning: 'かわな', type: 'surname' },
  { word: '目山', meaning: 'めやま', type: 'surname' },
  { word: '山目', meaning: 'やまめ', type: 'general' },
  { word: '目田', meaning: 'めだ', type: 'surname' },
  { word: '田目', meaning: 'ため', type: 'general' },
  { word: '目川', meaning: 'めかわ', type: 'surname' },
  { word: '川目', meaning: 'かわめ', type: 'surname' },
  { word: '力山', meaning: 'りきざん', type: 'general' },
  { word: '山力', meaning: 'さんりき', type: 'general' },
  { word: '力田', meaning: 'りきた', type: 'surname' },
  { word: '田力', meaning: 'たりき', type: 'general' },
  { word: '力川', meaning: 'りきかわ', type: 'surname' },
  { word: '川力', meaning: 'かわりき', type: 'general' },
  { word: '林村', meaning: 'はやしむら', type: 'surname' },
  { word: '村林', meaning: 'むらばやし', type: 'surname' },
]
